import { getEnrollmentAvailability, type EnrollmentAvailabilityStatus } from "@/lib/enrollment-window"

export type MockCourse = {
  id: number
  title: string
  slug: string
  shortDescription: string
  description: string
  category: string
  level: string
  languageCode: string
  tags: string[]
  seoKeywords: string[]
  targetAudience: string
  requirements: string
  learningOutcomes: string[]
  metaTitle: string
  metaDescription: string
  ogImageUrl: string
  canonicalUrl: string | null
  enrollmentOpen: boolean
  enrollmentStartAt: string | null
  enrollmentEndAt: string | null
  enrollmentCapacity: number | null
  enrollmentAppliedCount: number
  enrollmentStatus?: EnrollmentAvailabilityStatus
  enrollmentAvailable?: boolean
  remainingSeats?: number | null
  price: number
  discountPrice: number | null
  imageUrl: string
  createdAt: string
  purchaseCount: number
  reviewCount: number
  avgRating: number
  likeCount: number
  instructor: { id: number; nickname: string; email: string; profileImageUrl?: string | null }
  lastUpdatedAt: string
  includedFeatures: string[]
  relatedTopics: string[]
  sections: Array<{
    id: number
    moduleTitle: string
    title: string
    description: string
    active: boolean
    hasVideo: boolean
    hlsStatus: string | null
    durationSeconds: number
    isFreePreview: boolean
    previewVideoUrl?: string | null
    resources?: string[]
  }>
}

export const previewImages = [
  "/course-previews/course-101.png",
  "/course-previews/course-102.png",
  "/course-previews/course-103.png",
  "/course-previews/course-104.png",
  "/course-previews/course-105.png",
  "/course-previews/course-106.png",
  "/course-previews/course-107.png",
  "/course-previews/course-108.png",
  "/course-previews/course-201.png",
  "/course-previews/course-202.png",
  "/course-previews/course-203.png",
  "/course-previews/course-204.png",
  "/course-previews/course-205.png",
  "/course-previews/course-206.png",
  "/course-previews/course-207.png",
  "/course-previews/course-208.png",
  "/course-previews/course-209.png",
  "/course-previews/course-210.png",
  "/course-previews/course-211.png",
  "/course-previews/course-212.png",
  "/course-previews/course-213.png",
  "/course-previews/course-214.png",
  "/course-previews/course-215.png",
]

type MockLessonInput = {
  title: string
  description: string
  minutes: number
  resources?: string[]
}

type MockModuleInput = {
  moduleTitle: string
  lessons: MockLessonInput[]
}

const lessonPlan = (title: string, description: string, minutes: number, resources?: string[]): MockLessonInput => ({
  title,
  description,
  minutes,
  resources,
})

const modulePlan = (moduleTitle: string, lessons: MockLessonInput[]): MockModuleInput => ({
  moduleTitle,
  lessons,
})

function buildMockSections(courseId: number, modules: MockModuleInput[]): MockCourse["sections"] {
  let sequence = 0
  return modules.flatMap((module) =>
    module.lessons.map((lesson) => {
      sequence += 1
      return {
        id: courseId * 100 + sequence,
        moduleTitle: module.moduleTitle,
        title: lesson.title,
        description: lesson.description,
        active: true,
        hasVideo: false,
        hlsStatus: null,
        durationSeconds: lesson.minutes * 60,
        isFreePreview: false,
        previewVideoUrl: null,
        resources: lesson.resources,
      }
    }),
  )
}

function getTotalDurationSeconds(course: Pick<MockCourse, "sections">) {
  return course.sections.reduce((sum, section) => sum + section.durationSeconds, 0)
}

function formatCourseHours(totalSeconds: number) {
  const hours = Math.round((totalSeconds / 3600) * 10) / 10
  return `${Number.isInteger(hours) ? hours.toFixed(0) : hours.toFixed(1)}시간 분량 커리큘럼`
}

const lingoostSeoKeywords = [
  "링구스트",
  "Lingoost",
  "럿지",
  "주식회사 럿지",
  "온라인 강의",
  "강의 플랫폼",
  "강의 판매",
  "강의 등록",
  "강의자 모집",
  "시즌제 강의",
  "수강 신청",
  "계좌입금 강의",
  "HLS 강의",
  "강의 SEO",
]

type GameCourseInput = Omit<
  MockCourse,
  "category" | "languageCode" | "ogImageUrl" | "canonicalUrl" | "imageUrl" | "sections"
> & {
  modules: MockModuleInput[]
}

function gameCourse({ modules, ...course }: GameCourseInput): MockCourse {
  const imageUrl = `/course-previews/course-${course.id}.png`
  const sections = buildMockSections(course.id, modules)
  const totalDurationSeconds = getTotalDurationSeconds({ sections })
  const minimumDurationSeconds = 8 * 60 * 60
  const adjustedSections = totalDurationSeconds >= minimumDurationSeconds
    ? sections
    : sections.map((section) => ({
        ...section,
        durationSeconds: Math.ceil((section.durationSeconds * (minimumDurationSeconds / totalDurationSeconds)) / 60) * 60,
      }))

  return {
    ...course,
    category: "게임 개발",
    languageCode: "ko",
    ogImageUrl: imageUrl,
    canonicalUrl: null,
    imageUrl,
    sections: adjustedSections,
  }
}

function withDerivedMockStats(course: MockCourse) {
  const totalDurationSeconds = getTotalDurationSeconds(course)
  const durableFeatures = course.includedFeatures.filter(
    (feature) => !feature.includes("주문형 영상") && !/^\d+(\.\d+)?시간/.test(feature) && !/^\d+개 수업/.test(feature),
  )
  const seoKeywords = [...new Set([...course.seoKeywords, ...course.tags, course.category, ...lingoostSeoKeywords])]

  return {
    ...course,
    canonicalUrl: course.canonicalUrl ?? `https://www.lingoost.com/ko/course/${course.id}`,
    seoKeywords,
    relatedTopics: [...new Set([...course.relatedTopics, ...seoKeywords])],
    includedFeatures: [
      formatCourseHours(totalDurationSeconds),
      `${course.sections.length}개 수업`,
      ...durableFeatures,
    ].slice(0, 6),
  }
}

const additionalGameCourses: MockCourse[] = [
  gameCourse({
    id: 206,
    title: "Unreal Engine 5 멀티플레이어 슈터",
    slug: "unreal-engine-5-multiplayer-shooter",
    shortDescription: "Replication, 세션, 무기 시스템, 서버 권한 구조로 온라인 슈터 프로토타입을 만듭니다.",
    description:
      "Unreal Engine 5에서 멀티플레이어 슈터를 만들며 네트워크 게임의 핵심 구조를 익힙니다. 캐릭터 동기화, 서버 권한 판정, 무기 발사, 데미지, 세션 생성, 랙 보정의 기초까지 포트폴리오에 넣기 좋은 온라인 전투 프로토타입으로 완성합니다.",
    level: "중급-고급",
    tags: ["Unreal Engine 5", "Multiplayer", "Replication", "C++", "Shooter"],
    seoKeywords: ["언리얼 멀티플레이어 강의", "UE5 Replication", "온라인 게임 개발", "슈터 게임 만들기", "Unreal C++ 네트워크"],
    targetAudience: "싱글플레이 게임을 만들어봤고, 온라인 게임 동기화와 서버 권한 구조를 제대로 이해하고 싶은 Unreal Engine 개발자",
    requirements: "Unreal Engine 기본 조작과 C++ 클래스 생성 경험이 필요합니다. 네트워크 기초 지식은 강의 안에서 정리합니다.",
    learningOutcomes: ["Replication과 RPC 구조 이해", "서버 권한 기반 무기/데미지 구현", "로비와 세션 생성 흐름 제작", "멀티플레이어 슈터 포트폴리오 프로토타입 완성"],
    metaTitle: "Unreal Engine 5 멀티플레이어 슈터 | 링구스트",
    metaDescription: "Unreal Engine 5 C++와 Replication으로 온라인 슈터 프로토타입을 만드는 게임 개발 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-06-28T14:59:59.000Z",
    enrollmentCapacity: 32,
    enrollmentAppliedCount: 19,
    price: 139000,
    discountPrice: 99000,
    createdAt: "2026-05-16T00:00:00.000Z",
    purchaseCount: 541,
    reviewCount: 67,
    avgRating: 4.86,
    likeCount: 214,
    instructor: { id: 9206, nickname: "넷코드마스터", email: "ue-network@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["Replication 체크리스트", "무기 시스템 예제", "세션 플로우 다이어그램", "플레이테스트 QA 시트"],
    relatedTopics: ["Unreal Engine 5", "Networking", "Replication", "Online shooter", "Dedicated server"],
    modules: [
      modulePlan("온라인 슈터 구조 설계", [
        lessonPlan("멀티플레이어 게임이 어려운 이유", "입력, 판정, 이동, UI가 네트워크에서 어떻게 달라지는지 전체 지도를 그립니다.", 22, ["multiplayer-map.pdf"]),
        lessonPlan("서버 권한과 클라이언트 예측", "무엇을 서버가 결정하고 무엇을 클라이언트가 먼저 보여줄지 기준을 세웁니다.", 24),
        lessonPlan("프로토타입 범위와 테스트 맵", "무기, 체력, 리스폰, 라운드 규칙을 작은 슈터 맵으로 제한합니다.", 21),
        lessonPlan("네트워크 디버깅 환경 준비", "PIE 다중 클라이언트, 네트워크 에뮬레이션, 로그 카테고리를 설정합니다.", 23),
      ]),
      modulePlan("Replication과 RPC", [
        lessonPlan("Replicated 변수와 OnRep", "체력, 탄약, 팀 색상 같은 상태가 클라이언트에 반영되는 흐름을 구현합니다.", 26),
        lessonPlan("Server RPC와 Client RPC", "발사 요청, 피격 알림, 사망 연출처럼 방향이 다른 메시지를 나눕니다.", 25),
        lessonPlan("Multicast를 쓸 때와 피할 때", "이펙트와 사운드처럼 모두에게 보여야 하는 이벤트를 안전하게 전파합니다.", 22),
        lessonPlan("네트워크 비용 줄이기", "불필요한 Tick 동기화와 큰 구조체 전송을 피하는 기준을 만듭니다.", 21),
      ]),
      modulePlan("캐릭터, 무기, 데미지", [
        lessonPlan("네트워크 캐릭터 이동 확인", "Character Movement가 기본 제공하는 동기화와 한계를 실습합니다.", 24),
        lessonPlan("무기 장착과 발사 입력", "서버에 발사를 요청하고 클라이언트에는 즉각적인 반응을 보여줍니다.", 26),
        lessonPlan("히트스캔과 투사체 선택", "총기별로 판정 방식을 나누고 데미지를 서버에서 확정합니다.", 25),
        lessonPlan("탄약, 재장전, 무기 교체", "플레이 감각을 해치지 않게 상태 동기화와 UI 업데이트를 연결합니다.", 23),
      ]),
      modulePlan("로비와 게임 흐름", [
        lessonPlan("메인 메뉴와 세션 생성", "호스트가 방을 만들고 클라이언트가 참가하는 기본 흐름을 구현합니다.", 24),
        lessonPlan("플레이어 준비 상태와 팀 배정", "로비에서 준비 완료, 팀 선택, 관전 상태를 관리합니다.", 22),
        lessonPlan("라운드 시작과 리스폰", "GameMode와 PlayerState를 사용해 점수와 리스폰 위치를 제어합니다.", 25),
        lessonPlan("매치 종료와 결과 UI", "승패, 개인 점수, 다시 시작 흐름을 정리합니다.", 21),
      ]),
      modulePlan("랙 보정과 플레이 테스트", [
        lessonPlan("핑과 지연을 체감하는 방법", "Net PktLag, PktLoss 옵션으로 실제 온라인 환경을 흉내냅니다.", 23),
        lessonPlan("기초 랙 보정 개념", "히트스캔 판정에서 서버 시점과 클라이언트 시점 차이를 이해합니다.", 25),
        lessonPlan("동기화 버그 추적", "한쪽 클라이언트에서만 보이는 버그를 로그와 리플레이로 좁힙니다.", 24),
        lessonPlan("온라인 프로토타입 제출 패키지", "실행 파일, 테스트 방법, 네트워크 제한사항을 README로 정리합니다.", 22, ["network-playtest-checklist.xlsx"]),
      ]),
    ],
  }),
  gameCourse({
    id: 207,
    title: "Gameplay Ability System 실전 액션 전투",
    slug: "unreal-gameplay-ability-system-combat",
    shortDescription: "GAS로 스킬, 쿨다운, 버프, 데미지 계산이 있는 액션 전투 시스템을 구현합니다.",
    description:
      "Unreal Engine의 Gameplay Ability System을 사용해 확장 가능한 액션 전투 구조를 만듭니다. Attribute, Gameplay Effect, Gameplay Ability, 태그, 쿨다운, 코스트, UI 연동까지 실제 RPG/액션 게임에서 재사용할 수 있는 방식으로 설계합니다.",
    level: "고급",
    tags: ["Unreal Engine 5", "GAS", "Gameplay Ability System", "Action Combat", "C++"],
    seoKeywords: ["Gameplay Ability System 강의", "Unreal GAS", "언리얼 액션 전투", "UE5 RPG 스킬 시스템", "게임 전투 시스템"],
    targetAudience: "Unreal Engine으로 RPG나 액션 게임을 만들고 있고 스킬/버프/데미지 구조를 실무형으로 정리하고 싶은 개발자",
    requirements: "Unreal C++와 블루프린트 기본 사용 경험이 필요합니다. UE5 캐릭터/입력 시스템을 다뤄본 수강생에게 적합합니다.",
    learningOutcomes: ["GAS 핵심 개념과 클래스 구조 이해", "스킬, 쿨다운, 코스트, 버프 구현", "Attribute와 데미지 계산 설계", "UI와 전투 피드백까지 연결한 액션 전투 완성"],
    metaTitle: "Gameplay Ability System 실전 액션 전투 | 링구스트",
    metaDescription: "Unreal Engine Gameplay Ability System으로 스킬, 버프, 쿨다운, 데미지 계산을 구현하는 고급 게임 개발 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-07-02T14:59:59.000Z",
    enrollmentCapacity: 28,
    enrollmentAppliedCount: 15,
    price: 129000,
    discountPrice: 99000,
    createdAt: "2026-05-16T00:00:00.000Z",
    purchaseCount: 438,
    reviewCount: 53,
    avgRating: 4.9,
    likeCount: 198,
    instructor: { id: 9207, nickname: "컴뱃시스템즈", email: "gas@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["GAS 클래스 맵", "스킬 데이터 테이블", "전투 태그 규칙표", "액션 전투 샘플 프로젝트"],
    relatedTopics: ["Unreal Engine 5", "Gameplay Ability System", "RPG combat", "Action game", "C++"],
    modules: [
      modulePlan("GAS 도입과 프로젝트 구조", [
        lessonPlan("왜 GAS를 쓰는가", "단순 전투 스크립트와 GAS 기반 구조가 유지보수에서 어떻게 달라지는지 비교합니다.", 22, ["gas-architecture.pdf"]),
        lessonPlan("AbilitySystemComponent 배치", "캐릭터, PlayerState, AI에 ASC를 어디에 둘지 프로젝트 기준으로 판단합니다.", 25),
        lessonPlan("AttributeSet 설계", "체력, 마나, 스태미나, 공격력, 방어력의 책임을 나눕니다.", 24),
        lessonPlan("Gameplay Tag 네이밍 규칙", "상태, 입력, 이펙트, 스킬 계층을 충돌 없이 관리하는 규칙을 만듭니다.", 22),
      ]),
      modulePlan("Ability와 입력 연결", [
        lessonPlan("기본 공격 Ability 만들기", "입력, 애니메이션, 데미지 타이밍을 Ability Task로 연결합니다.", 26),
        lessonPlan("스킬 슬롯과 입력 매핑", "키보드/패드 입력과 스킬 슬롯을 데이터 기반으로 연결합니다.", 24),
        lessonPlan("쿨다운과 코스트 처리", "Gameplay Effect로 스킬 사용 비용과 재사용 대기시간을 구성합니다.", 25),
        lessonPlan("취소, 인터럽트, 콤보", "스킬이 끊기거나 다음 스킬로 이어지는 조건을 태그로 제어합니다.", 24),
      ]),
      modulePlan("데미지와 상태 효과", [
        lessonPlan("Execution Calculation 이해", "공격력, 방어력, 치명타 같은 계산을 서버 권한 로직으로 분리합니다.", 25),
        lessonPlan("버프와 디버프 만들기", "이동 속도 증가, 화상, 방어력 감소 같은 상태 효과를 구성합니다.", 23),
        lessonPlan("면역과 중첩 규칙", "같은 버프가 여러 번 들어올 때의 지속 시간과 스택 규칙을 정합니다.", 22),
        lessonPlan("피격 반응과 넉백", "전투 계산 결과를 애니메이션, VFX, 카메라 반응으로 전달합니다.", 24),
      ]),
      modulePlan("AI와 보스 패턴", [
        lessonPlan("AI가 Ability를 쓰게 만들기", "Behavior Tree와 Gameplay Ability를 연결하는 구조를 만듭니다.", 24),
        lessonPlan("보스 패턴 데이터화", "스킬 후보, 거리, 체력 구간, 쿨다운에 따라 패턴을 고르게 합니다.", 25),
        lessonPlan("위험 범위 표시", "공격 전에 바닥 경고와 타이밍 UI를 표시합니다.", 22),
        lessonPlan("전투 난이도 튜닝", "데미지, 쿨다운, 슈퍼아머, 회피 타이밍을 표로 조정합니다.", 23, ["combat-tuning-sheet.xlsx"]),
      ]),
      modulePlan("UI, 저장, 포트폴리오", [
        lessonPlan("스킬 UI와 쿨다운 표시", "쿨다운, 코스트 부족, 사용 가능 상태를 HUD에 표시합니다.", 23),
        lessonPlan("캐릭터 성장과 스킬 해금", "레벨 또는 퀘스트 조건에 따라 스킬을 부여하는 흐름을 만듭니다.", 24),
        lessonPlan("전투 로그와 디버그 화면", "데미지 계산과 태그 상태를 디버그 UI로 확인합니다.", 22),
        lessonPlan("전투 시스템 포트폴리오 정리", "스킬 구조, 클래스 다이어그램, 플레이 영상을 함께 제출합니다.", 21),
      ]),
    ],
  }),
  gameCourse({
    id: 208,
    title: "Unity Netcode 협동 생존 게임",
    slug: "unity-netcode-coop-survival",
    shortDescription: "Unity Netcode로 로비, 동기화, 아이템, 적 AI가 있는 협동 생존 게임을 만듭니다.",
    description:
      "Unity와 Netcode for GameObjects를 사용해 2-4인 협동 생존 게임 프로토타입을 제작합니다. 로비, 플레이어 스폰, 네트워크 변수, 서버 RPC, 아이템 줍기, 적 AI, 웨이브, 결과 화면까지 온라인 협동 게임의 핵심 루프를 실습합니다.",
    level: "중급",
    tags: ["Unity", "Netcode", "C#", "Co-op", "Survival"],
    seoKeywords: ["Unity Netcode 강의", "유니티 멀티플레이어", "협동 게임 만들기", "온라인 생존 게임", "C# 네트워크 게임"],
    targetAudience: "Unity 싱글플레이 게임을 만들어봤고 온라인 협동 게임으로 확장하고 싶은 개발자와 포트폴리오 준비생",
    requirements: "Unity와 C# 기본 경험이 필요합니다. 네트워크 게임 개발은 처음이어도 따라올 수 있게 구성합니다.",
    learningOutcomes: ["Unity Netcode 기본 구조 이해", "로비와 플레이어 동기화 구현", "아이템/적 AI/웨이브 네트워크 처리", "협동 생존 게임 프로토타입 완성"],
    metaTitle: "Unity Netcode 협동 생존 게임 | 링구스트",
    metaDescription: "Unity Netcode와 C#으로 2-4인 협동 생존 게임 프로토타입을 만드는 게임 개발 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-06-25T14:59:59.000Z",
    enrollmentCapacity: 36,
    enrollmentAppliedCount: 22,
    price: 119000,
    discountPrice: 89000,
    createdAt: "2026-05-17T00:00:00.000Z",
    purchaseCount: 624,
    reviewCount: 78,
    avgRating: 4.78,
    likeCount: 236,
    instructor: { id: 9208, nickname: "코옵메이커", email: "unity-netcode@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["Netcode 샘플 프로젝트", "로비 상태표", "웨이브 밸런스 시트", "온라인 QA 체크리스트"],
    relatedTopics: ["Unity", "Netcode for GameObjects", "Co-op game", "Survival game", "C#"],
    modules: [
      modulePlan("협동 생존 게임 구조", [
        lessonPlan("온라인 협동 게임의 핵심 루프", "탐색, 파밍, 전투, 탈출 목표를 작은 프로토타입으로 정리합니다.", 21, ["coop-loop-map.pdf"]),
        lessonPlan("Netcode 프로젝트 준비", "패키지 설치, NetworkManager, Transport, 테스트 빌드 구성을 세팅합니다.", 23),
        lessonPlan("호스트와 클라이언트 실행", "에디터와 빌드 클라이언트를 함께 띄워 디버깅하는 방법을 익힙니다.", 22),
        lessonPlan("네트워크 오브젝트 규칙", "프리팹 등록, NetworkObject, 소유권 개념을 실제 게임 오브젝트로 이해합니다.", 24),
      ]),
      modulePlan("플레이어 동기화", [
        lessonPlan("플레이어 스폰과 닉네임", "접속한 플레이어를 안전하게 스폰하고 이름표를 동기화합니다.", 23),
        lessonPlan("이동과 애니메이션 동기화", "NetworkTransform과 Animator 상태를 협동 게임에 맞게 설정합니다.", 24),
        lessonPlan("상호작용 권한 처리", "문 열기, 아이템 줍기, 버튼 누르기를 서버에서 검증합니다.", 24),
        lessonPlan("체력과 다운 상태", "플레이어가 쓰러지고 팀원이 부활시키는 상태를 구현합니다.", 23),
      ]),
      modulePlan("아이템과 인벤토리", [
        lessonPlan("네트워크 아이템 스폰", "맵에 생성된 아이템을 모든 플레이어에게 같은 상태로 보여줍니다.", 24),
        lessonPlan("줍기와 버리기", "아이템 소유권을 서버가 관리하고 인벤토리에 반영합니다.", 23),
        lessonPlan("소모품과 장비 효과", "회복 아이템, 탄약, 장비 버프가 각 플레이어 상태에 적용되게 합니다.", 22),
        lessonPlan("파밍 테이블과 희귀도", "아이템 등장 확률과 밸런스를 데이터 테이블로 조정합니다.", 21),
      ]),
      modulePlan("적 AI와 웨이브", [
        lessonPlan("서버 권한 적 스폰", "적이 서버에서 생성되고 모든 클라이언트에 동기화되는 흐름을 만듭니다.", 24),
        lessonPlan("타겟 선택과 추적", "가장 가까운 플레이어, 소음, 시야를 기준으로 타겟을 바꿉니다.", 23),
        lessonPlan("데미지와 피격 피드백", "서버 판정 데미지와 클라이언트 VFX를 분리합니다.", 22),
        lessonPlan("웨이브 난이도 조정", "시간, 인원 수, 생존 상태에 따라 적 수와 보상을 조정합니다.", 23, ["coop-wave-balance.xlsx"]),
      ]),
      modulePlan("로비, 결과, 제출", [
        lessonPlan("로비 준비 상태", "플레이어 준비, 캐릭터 선택, 시작 버튼 권한을 구현합니다.", 22),
        lessonPlan("탈출 목표와 승리 조건", "제한 시간 안에 목표를 완료하고 탈출하는 흐름을 만듭니다.", 23),
        lessonPlan("결과 화면과 보상", "팀 기여도, 생존 시간, 획득 아이템을 결과 UI로 정리합니다.", 21),
        lessonPlan("멀티플레이어 포트폴리오 영상", "두 클라이언트 화면을 나란히 보여주는 제출 영상을 만듭니다.", 21),
      ]),
    ],
  }),
  gameCourse({
    id: 209,
    title: "게임 AI Behavior Tree와 Utility AI",
    slug: "game-ai-behavior-tree-utility-ai",
    shortDescription: "순찰, 추적, 전투 판단, 보스 패턴을 Behavior Tree와 Utility AI로 구현합니다.",
    description:
      "게임 AI를 단순 추적 스크립트에서 벗어나 재사용 가능한 의사결정 구조로 설계합니다. Behavior Tree, Blackboard, 감지 시스템, 상태 전이, Utility Score, 보스 패턴 선택, 디버깅 뷰까지 실제 프로젝트에 붙일 수 있는 AI 흐름을 다룹니다.",
    level: "중급",
    tags: ["Game AI", "Behavior Tree", "Utility AI", "Unreal Engine", "Unity"],
    seoKeywords: ["게임 AI 강의", "Behavior Tree 강의", "Utility AI", "보스 AI 만들기", "적 AI 프로그래밍"],
    targetAudience: "기본 이동과 전투는 구현했지만 적 AI가 어색하게 느껴지는 게임 개발자, 보스 패턴과 NPC 판단 로직을 체계화하고 싶은 수강생",
    requirements: "Unity 또는 Unreal 중 하나로 간단한 캐릭터 이동과 전투를 만들어본 경험이 있으면 좋습니다.",
    learningOutcomes: ["AI 상태와 의사결정 모델링", "순찰/추적/전투 Behavior Tree 구현", "Utility Score 기반 행동 선택", "보스 패턴과 디버깅 도구 제작"],
    metaTitle: "게임 AI Behavior Tree와 Utility AI | 링구스트",
    metaDescription: "Behavior Tree와 Utility AI로 순찰, 추적, 전투 판단, 보스 패턴을 구현하는 게임 AI 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-06-30T14:59:59.000Z",
    enrollmentCapacity: 40,
    enrollmentAppliedCount: 26,
    price: 99000,
    discountPrice: 79000,
    createdAt: "2026-05-17T00:00:00.000Z",
    purchaseCount: 871,
    reviewCount: 116,
    avgRating: 4.74,
    likeCount: 302,
    instructor: { id: 9209, nickname: "AI디렉터", email: "game-ai@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["AI 상태 설계표", "보스 패턴 데이터 예제", "디버깅 오버레이 가이드", "밸런스 튜닝 시트"],
    relatedTopics: ["Game AI", "Behavior Tree", "Utility AI", "Boss AI", "NPC decision making"],
    modules: [
      modulePlan("게임 AI 설계 기초", [
        lessonPlan("좋은 적 AI는 똑똑한 AI가 아니다", "플레이어가 이해할 수 있고 재미를 만드는 AI 기준을 세웁니다.", 20, ["game-ai-design-notes.pdf"]),
        lessonPlan("감지, 판단, 행동의 분리", "시야, 소리, 거리, 체력 정보를 행동 선택과 분리해 설계합니다.", 22),
        lessonPlan("상태 머신과 Behavior Tree 비교", "각 구조가 잘 맞는 상황과 섞어 쓰는 기준을 봅니다.", 22),
        lessonPlan("AI 디버깅을 위한 표시 도구", "현재 목표, 상태, 점수를 화면에 보여주는 오버레이를 설계합니다.", 21),
      ]),
      modulePlan("순찰과 추적", [
        lessonPlan("Waypoints와 순찰 루프", "정해진 경로와 랜덤 경로를 모두 지원하는 순찰 구조를 만듭니다.", 23),
        lessonPlan("시야각과 발견 상태", "거리, 각도, 장애물 체크로 플레이어 발견을 판정합니다.", 24),
        lessonPlan("추적과 수색 상태", "플레이어를 놓쳤을 때 마지막 위치를 수색하는 흐름을 만듭니다.", 24),
        lessonPlan("소리 이벤트 반응", "발소리나 충돌 소음에 AI가 반응하도록 이벤트를 전달합니다.", 21),
      ]),
      modulePlan("전투 판단", [
        lessonPlan("공격 거리와 회피 판단", "근거리/원거리 공격, 후퇴, 엄폐를 조건으로 나눕니다.", 23),
        lessonPlan("쿨다운과 우선순위", "강한 공격을 반복하지 않도록 행동별 대기시간과 점수를 둡니다.", 22),
        lessonPlan("협동 AI와 역할 분배", "여러 적이 동시에 달려들지 않고 압박, 원거리, 회피 역할을 나누게 합니다.", 24),
        lessonPlan("난이도별 AI 파라미터", "반응 속도, 명중률, 추적 시간, 공격 빈도를 데이터로 분리합니다.", 22),
      ]),
      modulePlan("Utility AI", [
        lessonPlan("Utility Score란 무엇인가", "체력, 거리, 위험도, 기회 값을 점수로 바꿔 행동을 선택합니다.", 24),
        lessonPlan("점수 곡선 만들기", "선형 점수 대신 곡선을 사용해 자연스러운 행동 전환을 만듭니다.", 23),
        lessonPlan("행동 후보와 선택 로그", "AI가 왜 그 행동을 골랐는지 디버그 로그로 확인합니다.", 22),
        lessonPlan("Behavior Tree와 Utility 혼합", "전체 흐름은 트리로, 세부 전투 판단은 점수로 처리합니다.", 23, ["utility-ai-score-sheet.xlsx"]),
      ]),
      modulePlan("보스 패턴과 포트폴리오", [
        lessonPlan("보스 페이즈 구조", "체력 구간과 전투 시간에 따라 패턴 후보를 바꿉니다.", 23),
        lessonPlan("텔레그래프와 회피 가능성", "강한 공격 전에 경고 연출과 피할 시간을 제공합니다.", 22),
        lessonPlan("패턴 반복 방지", "같은 패턴이 연속으로 나오지 않게 히스토리를 관리합니다.", 21),
        lessonPlan("AI 쇼케이스 영상 구성", "순찰, 추적, 전투, 보스 판단을 짧은 포트폴리오 클립으로 정리합니다.", 21),
      ]),
    ],
  }),
  gameCourse({
    id: 210,
    title: "절차적 던전 생성과 레벨 툴 제작",
    slug: "procedural-dungeon-level-tool",
    shortDescription: "그리드, 룸 배치, 복도 연결, 스폰 규칙을 이용해 재사용 가능한 던전 생성 툴을 만듭니다.",
    description:
      "매번 손으로 레벨을 만들지 않고 규칙 기반으로 던전을 생성하는 방법을 배웁니다. 룸 템플릿, 그래프 연결, 충돌 검사, 난이도 곡선, 적/보상 스폰, 에디터 버튼과 미리보기까지 레벨 디자이너가 함께 쓸 수 있는 제작 툴로 완성합니다.",
    level: "중급",
    tags: ["Procedural Generation", "Level Design", "Dungeon", "Unity", "Unreal Engine"],
    seoKeywords: ["절차적 생성 강의", "던전 생성 알고리즘", "게임 레벨 툴", "프로시저럴 레벨 디자인", "로그라이크 던전 만들기"],
    targetAudience: "로그라이크, 액션 RPG, 탐험형 게임에서 반복 가능한 레벨 생성 시스템을 만들고 싶은 개발자와 레벨 디자이너",
    requirements: "배열, 그래프, 좌표계에 대한 기본 이해가 있으면 좋습니다. 예제는 엔진에 종속되지 않게 설명합니다.",
    learningOutcomes: ["룸 기반 던전 생성 알고리즘 구현", "복도 연결과 충돌 검사 설계", "스폰/보상/난이도 규칙 데이터화", "레벨 디자이너용 미리보기 툴 제작"],
    metaTitle: "절차적 던전 생성과 레벨 툴 제작 | 링구스트",
    metaDescription: "룸 배치, 그래프 연결, 스폰 규칙으로 재사용 가능한 절차적 던전 생성 툴을 만드는 게임 개발 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-07-04T14:59:59.000Z",
    enrollmentCapacity: 34,
    enrollmentAppliedCount: 20,
    price: 109000,
    discountPrice: 84000,
    createdAt: "2026-05-18T00:00:00.000Z",
    purchaseCount: 492,
    reviewCount: 62,
    avgRating: 4.81,
    likeCount: 207,
    instructor: { id: 9210, nickname: "레벨툴러", email: "procgen@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["던전 생성 의사코드", "룸 템플릿 샘플", "스폰 규칙표", "레벨 QA 체크리스트"],
    relatedTopics: ["Procedural generation", "Dungeon generation", "Level design", "Tool development", "Roguelike"],
    modules: [
      modulePlan("절차적 레벨 디자인 기초", [
        lessonPlan("랜덤과 규칙의 균형", "완전 랜덤이 왜 재미없는지 보고 플레이 가능한 규칙을 정의합니다.", 21, ["procgen-design-map.pdf"]),
        lessonPlan("그리드와 좌표계", "던전을 셀 단위로 표현하고 룸 배치를 검증하는 기초를 만듭니다.", 22),
        lessonPlan("룸 템플릿 설계", "입구, 출구, 크기, 난이도, 테마 정보를 룸 데이터로 분리합니다.", 23),
        lessonPlan("생성 결과를 빠르게 보는 도구", "시드 값, 생성 버튼, 미니맵 미리보기 UI를 준비합니다.", 22),
      ]),
      modulePlan("룸 배치와 연결", [
        lessonPlan("랜덤 워크와 BSP 방식 비교", "던전 구조에 따라 어떤 생성 방식이 어울리는지 실습합니다.", 24),
        lessonPlan("룸 충돌 검사", "겹치는 방, 너무 가까운 방, 맵 밖으로 나간 방을 제거합니다.", 23),
        lessonPlan("그래프 기반 연결", "방 사이의 연결 후보를 만들고 최소 연결성을 보장합니다.", 25),
        lessonPlan("복도 생성과 문 배치", "룸 입구와 복도를 자연스럽게 연결하고 막힌 길을 줄입니다.", 24),
      ]),
      modulePlan("스폰과 난이도", [
        lessonPlan("적 스폰 포인트 규칙", "시야, 거리, 방 타입을 기준으로 스폰 위치를 고릅니다.", 22),
        lessonPlan("보상과 위험도 배치", "위험한 방일수록 보상이 커지는 간단한 경제를 만듭니다.", 22),
        lessonPlan("난이도 곡선 데이터화", "층수, 방 순서, 플레이어 진행도에 따라 적 조합을 바꿉니다.", 23),
        lessonPlan("시드 기반 재현성", "버그가 난 던전을 같은 시드로 다시 생성해 디버깅합니다.", 21),
      ]),
      modulePlan("레벨 툴과 디자이너 UX", [
        lessonPlan("에디터 버튼과 파라미터", "방 수, 크기, 테마, 난이도를 툴에서 조절하게 합니다.", 23),
        lessonPlan("생성 실패 이유 표시", "왜 던전 생성이 실패했는지 로그와 색상으로 보여줍니다.", 21),
        lessonPlan("룸 잠금과 부분 재생성", "디자이너가 좋은 방은 유지하고 나머지만 다시 뽑을 수 있게 합니다.", 24),
        lessonPlan("생성 결과 저장", "자동 생성된 레벨을 실제 씬이나 데이터 파일로 저장합니다.", 22),
      ]),
      modulePlan("완성도와 제출", [
        lessonPlan("플레이 가능성 QA", "막힌 길, 지나치게 긴 동선, 불공정한 스폰을 검사합니다.", 22),
        lessonPlan("미니맵과 탐험 피드백", "플레이어가 생성된 구조를 이해할 수 있게 지도와 표시를 붙입니다.", 21),
        lessonPlan("던전 쇼케이스 만들기", "서로 다른 시드의 결과를 비교하는 짧은 영상을 촬영합니다.", 20),
        lessonPlan("툴 포트폴리오 문서화", "알고리즘, 파라미터, 결과 이미지를 한 문서로 정리합니다.", 20, ["level-tool-portfolio-template.md"]),
      ]),
    ],
  }),
  gameCourse({
    id: 211,
    title: "게임 UI/UX와 HUD 시스템 설계",
    slug: "game-ui-ux-hud-system",
    shortDescription: "HUD, 인벤토리, 스킬 슬롯, 패드/키보드 입력까지 게임 UI를 실제 프로젝트처럼 만듭니다.",
    description:
      "게임 UI가 예쁘게 보이는 것을 넘어 플레이를 돕는 정보 구조가 되도록 설계합니다. HUD, 인벤토리, 스킬 슬롯, 툴팁, 설정 메뉴, 패드/키보드 내비게이션, 접근성 옵션까지 실제 액션 RPG UI 흐름으로 구현합니다.",
    level: "입문-중급",
    tags: ["Game UI", "UX", "HUD", "Unreal Engine", "Unity"],
    seoKeywords: ["게임 UI 강의", "게임 UX", "HUD 만들기", "인벤토리 UI", "게임 메뉴 UI", "UI 포트폴리오"],
    targetAudience: "게임 화면을 만들 때 정보 배치와 조작 흐름이 항상 어색했던 개발자, UI 디자이너와 협업하는 게임 개발자",
    requirements: "Unity 또는 Unreal에서 기본 UI 위젯을 만들어본 경험이 있으면 좋습니다.",
    learningOutcomes: ["플레이 정보를 우선순위로 나누는 방법", "HUD와 메뉴 UI 구현", "패드/키보드 내비게이션 설계", "게임 UI 포트폴리오 화면 구성"],
    metaTitle: "게임 UI/UX와 HUD 시스템 설계 | 링구스트",
    metaDescription: "HUD, 인벤토리, 스킬 슬롯, 설정 메뉴까지 실제 플레이에 맞는 게임 UI/UX를 설계하고 구현하는 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-06-23T14:59:59.000Z",
    enrollmentCapacity: 44,
    enrollmentAppliedCount: 29,
    price: 89000,
    discountPrice: 69000,
    createdAt: "2026-05-18T00:00:00.000Z",
    purchaseCount: 738,
    reviewCount: 96,
    avgRating: 4.76,
    likeCount: 271,
    instructor: { id: 9211, nickname: "HUD디자이너", email: "game-ui@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["HUD 와이어프레임", "인벤토리 UI 프리셋", "패드 내비게이션 체크리스트", "UI 접근성 기준표"],
    relatedTopics: ["Game UI", "HUD", "UX", "Inventory", "Accessibility"],
    modules: [
      modulePlan("게임 UI 정보 구조", [
        lessonPlan("좋은 HUD가 하는 일", "체력, 목표, 위험, 입력 힌트가 플레이 중 언제 보여야 하는지 정리합니다.", 20, ["hud-priority-map.pdf"]),
        lessonPlan("액션 RPG 화면 분해", "미니맵, 스킬 슬롯, 퀘스트, 알림 영역을 실제 플레이 기준으로 나눕니다.", 22),
        lessonPlan("UI 상태와 게임 상태 연결", "전투 중, 메뉴 중, 컷신 중에 입력과 표시가 어떻게 달라지는지 설계합니다.", 22),
        lessonPlan("프로토타입용 와이어프레임", "이미지 툴 없이 엔진 안에서 빠르게 테스트할 UI 틀을 만듭니다.", 21),
      ]),
      modulePlan("HUD 구현", [
        lessonPlan("체력과 스태미나 표시", "값 변화가 자연스럽게 보이도록 즉시값과 지연값을 함께 표시합니다.", 22),
        lessonPlan("스킬 슬롯과 쿨다운", "스킬 사용 가능, 쿨다운, 코스트 부족 상태를 시각적으로 구분합니다.", 23),
        lessonPlan("피격 방향과 위험 알림", "화면 가장자리, 색, 애니메이션을 이용해 플레이어 주의를 유도합니다.", 21),
        lessonPlan("퀘스트와 목표 UI", "항상 보일 정보와 필요할 때만 뜨는 정보를 나눕니다.", 20),
      ]),
      modulePlan("메뉴와 인벤토리", [
        lessonPlan("인벤토리 그리드와 아이템 상세", "선택, 장착, 버리기, 비교 흐름을 작은 데이터 구조로 만듭니다.", 24),
        lessonPlan("툴팁과 비교 패널", "아이템 효과를 플레이어가 빠르게 판단하도록 정보 순서를 정합니다.", 22),
        lessonPlan("설정 메뉴와 저장", "그래픽, 오디오, 조작 설정을 저장하고 즉시 반영합니다.", 22),
        lessonPlan("일시정지와 입력 모드", "UI 입력과 게임 입력이 충돌하지 않도록 모드를 전환합니다.", 21),
      ]),
      modulePlan("입력과 접근성", [
        lessonPlan("패드 내비게이션", "포커스 이동, 기본 선택, 뒤로가기 흐름을 패드 기준으로 점검합니다.", 23),
        lessonPlan("키보드/마우스와 터치 대응", "같은 UI가 입력 장치에 따라 자연스럽게 동작하도록 분기합니다.", 22),
        lessonPlan("색약과 가독성 기준", "색만으로 상태를 전달하지 않는 UI 규칙을 적용합니다.", 20),
        lessonPlan("해상도와 세이프존", "울트라와이드, 모바일, TV 화면에서 UI가 잘리지 않도록 테스트합니다.", 21, ["ui-safezone-checklist.xlsx"]),
      ]),
      modulePlan("UI 포트폴리오 완성", [
        lessonPlan("전투 HUD 쇼케이스", "전투 중 정보 변화가 잘 보이는 20초 클립을 만듭니다.", 20),
        lessonPlan("메뉴 플로우 영상", "인벤토리, 장착, 설정, 저장 흐름을 연속 화면으로 보여줍니다.", 20),
        lessonPlan("UI 시스템 설명서", "데이터 구조, 위젯 트리, 입력 흐름을 문서로 정리합니다.", 19),
        lessonPlan("실무 리뷰 기준으로 다듬기", "불필요한 장식보다 플레이 가독성과 입력 안정성을 우선해 개선합니다.", 20),
      ]),
    ],
  }),
  gameCourse({
    id: 212,
    title: "게임 오디오와 인터랙티브 사운드",
    slug: "interactive-game-audio-implementation",
    shortDescription: "발소리, 전투음, 환경음, 믹싱 상태를 게임 이벤트에 맞춰 동적으로 재생합니다.",
    description:
      "게임 오디오는 단순히 효과음을 붙이는 일이 아니라 플레이 상황을 읽고 반응하는 시스템입니다. 발소리 표면 감지, 전투 피드백, 환경 앰비언스, 상태별 믹싱, 오디오 이벤트 구조, 성능 관리까지 실제 게임 프로젝트에 필요한 오디오 구현 흐름을 다룹니다.",
    level: "입문-중급",
    tags: ["Game Audio", "Sound Design", "Unity", "Unreal Engine", "Audio Middleware"],
    seoKeywords: ["게임 오디오 강의", "게임 사운드 디자인", "인터랙티브 오디오", "발소리 시스템", "게임 효과음 구현"],
    targetAudience: "게임에 사운드를 넣었지만 밋밋하게 느껴졌던 개발자, 오디오 디자이너와 협업해야 하는 인디 개발자",
    requirements: "Unity 또는 Unreal에서 오브젝트와 이벤트를 다뤄본 경험이 있으면 좋습니다.",
    learningOutcomes: ["게임 이벤트 기반 사운드 구조 설계", "발소리와 표면별 사운드 구현", "전투/환경 오디오 믹싱", "오디오 QA와 성능 관리"],
    metaTitle: "게임 오디오와 인터랙티브 사운드 | 링구스트",
    metaDescription: "발소리, 전투음, 환경음, 믹싱 상태를 게임 이벤트에 맞춰 구현하는 인터랙티브 게임 오디오 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-06-27T14:59:59.000Z",
    enrollmentCapacity: 38,
    enrollmentAppliedCount: 18,
    price: 79000,
    discountPrice: 59000,
    createdAt: "2026-05-19T00:00:00.000Z",
    purchaseCount: 416,
    reviewCount: 51,
    avgRating: 4.73,
    likeCount: 174,
    instructor: { id: 9212, nickname: "사운드루프", email: "game-audio@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["오디오 이벤트 맵", "발소리 표면 테이블", "믹싱 상태표", "사운드 QA 체크리스트"],
    relatedTopics: ["Game audio", "Interactive sound", "Sound design", "Footstep system", "Audio mixing"],
    modules: [
      modulePlan("게임 오디오 구조", [
        lessonPlan("효과음 파일을 붙이는 것과 시스템의 차이", "게임 상태와 이벤트가 오디오를 어떻게 제어해야 하는지 봅니다.", 20, ["audio-event-map.pdf"]),
        lessonPlan("사운드 카테고리 나누기", "UI, 플레이어, 적, 환경, 음악, 보이스를 믹싱 기준으로 나눕니다.", 21),
        lessonPlan("오디오 이벤트 네이밍", "나중에 바꿔도 코드가 흔들리지 않는 이벤트 이름 규칙을 만듭니다.", 20),
        lessonPlan("프로토타입 씬 준비", "발소리, 전투, 환경음을 한 번에 테스트할 작은 레벨을 만듭니다.", 21),
      ]),
      modulePlan("움직임과 상호작용 사운드", [
        lessonPlan("표면별 발소리", "바닥 재질에 따라 발소리가 달라지는 구조를 구현합니다.", 23),
        lessonPlan("점프, 착지, 구르기", "애니메이션 이벤트와 물리 상태를 소리 타이밍에 연결합니다.", 22),
        lessonPlan("문, 상자, 스위치 사운드", "월드 오브젝트 상호작용에 작은 소리 변화를 붙입니다.", 21),
        lessonPlan("거리 감쇠와 공간감", "3D 사운드 범위, 감쇠 곡선, 방향감을 조정합니다.", 22),
      ]),
      modulePlan("전투 사운드 디자인", [
        lessonPlan("공격 준비와 타격음", "스윙, 충돌, 피격, 방어음을 계층으로 나눕니다.", 22),
        lessonPlan("무기별 사운드 변주", "검, 활, 총기처럼 무기 유형별 재생 규칙을 만듭니다.", 21),
        lessonPlan("위험 알림과 피격 피드백", "플레이어가 소리만 듣고도 위험을 알 수 있게 신호를 설계합니다.", 22),
        lessonPlan("전투 믹싱 우선순위", "중요한 효과음이 음악이나 환경음에 묻히지 않도록 처리합니다.", 23),
      ]),
      modulePlan("환경음과 음악 상태", [
        lessonPlan("지역별 앰비언스", "숲, 동굴, 실내 공간마다 배경음을 전환합니다.", 21),
        lessonPlan("전투 진입 음악 전환", "탐험 음악에서 전투 음악으로 자연스럽게 바뀌는 상태를 만듭니다.", 22),
        lessonPlan("레이어드 음악 구조", "위험도, 체력, 보스 페이즈에 따라 음악 레이어를 추가합니다.", 22),
        lessonPlan("오디오 스냅샷과 믹스 상태", "일시정지, 수중, 저체력 같은 상태의 필터와 볼륨을 관리합니다.", 23),
      ]),
      modulePlan("성능, QA, 제출", [
        lessonPlan("동시 재생 수 관리", "너무 많은 사운드가 재생될 때 우선순위와 제한을 둡니다.", 20),
        lessonPlan("반복 청취 피로 줄이기", "피치, 볼륨, 샘플 변주로 반복감을 줄입니다.", 20),
        lessonPlan("오디오 QA 체크리스트", "누락, 너무 큰 소리, 잘못된 위치, 중복 재생을 점검합니다.", 19, ["audio-qa-checklist.xlsx"]),
        lessonPlan("오디오 구현 포트폴리오", "소리 없는 버전과 적용 버전을 비교하는 영상을 만듭니다.", 20),
      ]),
    ],
  }),
  gameCourse({
    id: 213,
    title: "Steam 인디게임 출시와 QA 파이프라인",
    slug: "steam-indie-game-release-qa",
    shortDescription: "스토어 페이지, 빌드 업로드, 테스트 체크리스트, 데모 공개까지 인디게임 출시 흐름을 정리합니다.",
    description:
      "게임을 만드는 것과 출시하는 것은 다른 문제입니다. 이 강의는 인디게임 팀이 데모와 정식 출시를 준비할 때 필요한 스토어 페이지 구성, 빌드 버전 관리, QA 체크리스트, 버그 리포트, 트레일러/스크린샷, 출시 후 핫픽스 루틴을 실전 운영 관점으로 다룹니다.",
    level: "입문-중급",
    tags: ["Indie Game", "Steam", "QA", "Release", "Production"],
    seoKeywords: ["스팀 출시 강의", "인디게임 출시", "게임 QA 체크리스트", "게임 데모 공개", "게임 출시 준비"],
    targetAudience: "게임 프로토타입은 있지만 출시 준비가 막막한 인디 개발자, 팀 프로젝트를 실제 공개 단계까지 가져가고 싶은 수강생",
    requirements: "완성 중인 게임 프로토타입이나 공개할 데모 빌드가 있으면 가장 좋습니다.",
    learningOutcomes: ["스토어 페이지와 데모 공개 준비", "빌드 버전 관리와 QA 체크리스트 구성", "버그 리포트와 핫픽스 루틴 설계", "출시 자료 패키지 완성"],
    metaTitle: "Steam 인디게임 출시와 QA 파이프라인 | 링구스트",
    metaDescription: "스토어 페이지, 빌드 업로드, QA 체크리스트, 데모 공개까지 인디게임 출시 흐름을 실전적으로 정리하는 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-07-01T14:59:59.000Z",
    enrollmentCapacity: 46,
    enrollmentAppliedCount: 33,
    price: 99000,
    discountPrice: 79000,
    createdAt: "2026-05-19T00:00:00.000Z",
    purchaseCount: 963,
    reviewCount: 132,
    avgRating: 4.79,
    likeCount: 344,
    instructor: { id: 9213, nickname: "인디프로듀서", email: "indie-release@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["출시 일정표", "QA 테스트 케이스", "버그 리포트 템플릿", "스토어 페이지 체크리스트"],
    relatedTopics: ["Indie game release", "Steam", "QA", "Game production", "Demo launch"],
    modules: [
      modulePlan("출시 준비의 전체 지도", [
        lessonPlan("프로토타입과 출시 빌드의 차이", "재미 검증용 빌드와 공개 가능한 빌드가 어떤 기준에서 다른지 정리합니다.", 20, ["release-roadmap.pdf"]),
        lessonPlan("출시 일정 역산", "스토어 공개, 데모, QA, 트레일러, 핫픽스 일정을 뒤에서부터 계산합니다.", 22),
        lessonPlan("버전 규칙과 변경 로그", "빌드 번호, 태그, 변경 내역을 팀원과 테스터가 이해하게 관리합니다.", 21),
        lessonPlan("출시 리스크 목록", "크래시, 세이브 손상, 성능 저하, 콘텐츠 누락 같은 리스크를 먼저 적습니다.", 20),
      ]),
      modulePlan("스토어 페이지 구성", [
        lessonPlan("장르와 핵심 훅 정리", "플레이어가 5초 안에 이해할 한 문장을 만듭니다.", 20),
        lessonPlan("스크린샷 선정 기준", "보기 좋은 컷보다 게임의 핵심 경험을 설명하는 컷을 고릅니다.", 21),
        lessonPlan("트레일러 구성", "첫 10초, 게임플레이, 특징, CTA의 순서를 잡습니다.", 22),
        lessonPlan("태그와 설명 작성", "검색과 추천에 영향을 주는 장르, 기능, 분위기 태그를 정리합니다.", 20),
      ]),
      modulePlan("QA 파이프라인", [
        lessonPlan("테스트 케이스 만들기", "튜토리얼, 저장, 옵션, 입력, 전투, 엔딩 흐름을 케이스로 나눕니다.", 23, ["qa-test-cases.xlsx"]),
        lessonPlan("버그 재현 정보 수집", "기기, OS, 버전, 세이브 파일, 재현 단계가 빠지지 않게 템플릿을 만듭니다.", 21),
        lessonPlan("크래시와 로그 확보", "플레이어에게 받을 로그 위치와 최소 정보를 문서화합니다.", 21),
        lessonPlan("우선순위 분류", "출시 전 반드시 고칠 문제와 나중에 고쳐도 되는 문제를 구분합니다.", 20),
      ]),
      modulePlan("데모와 플레이테스트", [
        lessonPlan("데모 범위 정하기", "게임의 장점을 보여주되 너무 많이 공개하지 않는 범위를 정합니다.", 21),
        lessonPlan("테스터 모집과 안내문", "테스트 목표, 피드백 양식, 플레이 시간, 비밀 유지 범위를 안내합니다.", 20),
        lessonPlan("피드백을 수정 과제로 바꾸기", "감상과 문제 제기를 실제 작업 티켓으로 바꿉니다.", 22),
        lessonPlan("데모 업데이트 루틴", "테스트 기간 중 언제, 무엇을, 어떻게 패치할지 정합니다.", 20),
      ]),
      modulePlan("출시 후 운영", [
        lessonPlan("출시 당일 체크리스트", "빌드, 가격, 공지, 커뮤니티, 소셜 채널을 순서대로 확인합니다.", 20),
        lessonPlan("핫픽스 판단 기준", "플레이 불가 문제와 밸런스 문제를 분리해 긴급도를 판단합니다.", 21),
        lessonPlan("리뷰와 커뮤니티 대응", "감정적으로 흔들리지 않게 공개 답변 기준을 세웁니다.", 19),
        lessonPlan("다음 업데이트 로드맵", "출시 후 데이터를 보고 어떤 콘텐츠와 수정이 우선인지 정합니다.", 20),
      ]),
    ],
  }),
  gameCourse({
    id: 214,
    title: "Unreal Sequencer 게임 시네마틱 제작",
    slug: "unreal-sequencer-game-cinematic",
    shortDescription: "카메라, 조명, 애니메이션, VFX를 Sequencer로 묶어 게임 트레일러 컷신을 만듭니다.",
    description:
      "Unreal Engine Sequencer를 활용해 게임 컷신과 트레일러용 시네마틱을 제작합니다. 카메라 블로킹, 조명, 캐릭터 애니메이션, VFX 타이밍, 렌더 설정, 편집 리듬까지 포트폴리오에 넣기 좋은 짧은 게임 시네마틱으로 완성합니다.",
    level: "입문-중급",
    tags: ["Unreal Engine 5", "Sequencer", "Cinematic", "Trailer", "Lighting"],
    seoKeywords: ["Unreal Sequencer 강의", "언리얼 시네마틱", "게임 트레일러 제작", "UE5 컷신", "게임 영상 포트폴리오"],
    targetAudience: "게임 프로젝트를 더 멋지게 보여주고 싶은 개발자, 환경 아트/캐릭터/이펙트 포트폴리오 영상을 만들고 싶은 수강생",
    requirements: "Unreal Engine 기본 조작 경험이 필요합니다. 영상 편집 경험은 없어도 됩니다.",
    learningOutcomes: ["Sequencer 카메라와 컷 구성", "조명과 VFX 타이밍 연출", "게임 컷신 블로킹과 렌더링", "포트폴리오용 시네마틱 영상 완성"],
    metaTitle: "Unreal Sequencer 게임 시네마틱 제작 | 링구스트",
    metaDescription: "Unreal Engine Sequencer로 카메라, 조명, 애니메이션, VFX를 묶어 게임 트레일러 컷신을 만드는 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-06-29T14:59:59.000Z",
    enrollmentCapacity: 35,
    enrollmentAppliedCount: 16,
    price: 89000,
    discountPrice: 69000,
    createdAt: "2026-05-20T00:00:00.000Z",
    purchaseCount: 377,
    reviewCount: 45,
    avgRating: 4.84,
    likeCount: 163,
    instructor: { id: 9214, nickname: "시네마틱룸", email: "sequencer@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["시네마틱 샷 리스트", "조명 프리셋 노트", "렌더 설정표", "트레일러 편집 체크리스트"],
    relatedTopics: ["Unreal Engine 5", "Sequencer", "Game cinematic", "Trailer", "Lighting"],
    modules: [
      modulePlan("시네마틱 기획과 샷 구성", [
        lessonPlan("게임 시네마틱의 역할", "게임플레이를 설명하는 컷과 분위기를 만드는 컷을 구분합니다.", 20, ["cinematic-shot-list.pdf"]),
        lessonPlan("30초 트레일러 구조", "훅, 세계관, 액션, 클로징을 짧은 영상 흐름으로 배치합니다.", 21),
        lessonPlan("샷 리스트 작성", "카메라 위치, 피사체, 움직임, 필요한 에셋을 표로 정리합니다.", 20),
        lessonPlan("레벨과 캐릭터 준비", "촬영용 맵, 캐릭터, 애니메이션, VFX 에셋을 정리합니다.", 21),
      ]),
      modulePlan("Sequencer 기본", [
        lessonPlan("시퀀스와 카메라 컷 트랙", "여러 카메라를 만들고 컷 트랙으로 연결합니다.", 22),
        lessonPlan("키프레임과 커브 편집", "카메라 이동 속도와 타이밍을 곡선으로 다듬습니다.", 23),
        lessonPlan("캐릭터 애니메이션 배치", "애니메이션 클립을 트랙에 올리고 위치와 타이밍을 맞춥니다.", 22),
        lessonPlan("이벤트 트랙 사용", "특정 프레임에 VFX, 사운드, 게임 이벤트를 실행합니다.", 21),
      ]),
      modulePlan("카메라와 조명", [
        lessonPlan("렌즈와 FOV 선택", "액션, 대화, 환경 샷에 맞는 초점거리와 시야각을 고릅니다.", 21),
        lessonPlan("카메라 블로킹", "샷의 주인공과 움직임이 명확하게 보이도록 카메라를 배치합니다.", 22),
        lessonPlan("키라이트와 림라이트", "캐릭터와 배경이 분리되도록 기본 조명 구조를 만듭니다.", 22),
        lessonPlan("색보정과 분위기", "Post Process Volume으로 장면의 톤과 대비를 정리합니다.", 21),
      ]),
      modulePlan("VFX, 사운드, 렌더", [
        lessonPlan("이펙트 타이밍 맞추기", "폭발, 포털, 타격 VFX가 카메라 컷과 어긋나지 않게 조정합니다.", 22),
        lessonPlan("사운드 임시 배치", "효과음과 음악을 임시로 넣어 편집 리듬을 잡습니다.", 20),
        lessonPlan("Movie Render Queue 설정", "해상도, 프레임, 안티앨리어싱, 출력 포맷을 설정합니다.", 23),
        lessonPlan("렌더 실패와 깜빡임 해결", "노출, LOD, 스트리밍, 모션블러 문제를 점검합니다.", 21),
      ]),
      modulePlan("포트폴리오 트레일러 완성", [
        lessonPlan("컷 편집과 길이 조절", "늘어지는 컷을 줄이고 액션의 박자를 맞춥니다.", 20),
        lessonPlan("자막과 타이틀 최소화", "이미지 자체가 프로젝트를 설명하도록 과한 글자를 줄입니다.", 19),
        lessonPlan("비포/애프터와 브레이크다운", "최종 영상과 제작 과정을 함께 보여주는 구성을 만듭니다.", 20),
        lessonPlan("업로드용 파일 정리", "고화질 원본, 압축본, 썸네일, 설명문을 묶습니다.", 19),
      ]),
    ],
  }),
  gameCourse({
    id: 215,
    title: "Roblox Studio UGC 미니게임 제작",
    slug: "roblox-studio-ugc-minigame",
    shortDescription: "Lua 스크립트, 라운드 규칙, 보상, 상점 UI로 플레이 가능한 Roblox 미니게임을 만듭니다.",
    description:
      "Roblox Studio로 짧고 반복 플레이가 가능한 UGC 미니게임을 제작합니다. 맵 구성, Lua 스크립트, 라운드 타이머, 플레이어 스폰, 보상, 상점 UI, 데이터 저장, 공개 전 테스트까지 입문자가 실제 공개 가능한 작은 게임을 완성합니다.",
    level: "입문",
    tags: ["Roblox Studio", "Lua", "UGC", "Mini Game", "Game Design"],
    seoKeywords: ["Roblox Studio 강의", "로블록스 게임 만들기", "Lua 게임 개발", "UGC 미니게임", "로블록스 입문"],
    targetAudience: "코딩을 게임으로 시작하고 싶은 입문자, Roblox Studio로 첫 공개 게임을 만들고 싶은 크리에이터",
    requirements: "프로그래밍 경험이 없어도 따라올 수 있습니다. Roblox Studio 설치와 계정이 필요합니다.",
    learningOutcomes: ["Roblox Studio 맵과 오브젝트 구성", "Lua로 게임 규칙 작성", "라운드/보상/상점 UI 구현", "공개 전 테스트와 업데이트 루틴 이해"],
    metaTitle: "Roblox Studio UGC 미니게임 제작 | 링구스트",
    metaDescription: "Roblox Studio와 Lua로 라운드, 보상, 상점 UI가 있는 UGC 미니게임을 만드는 게임 개발 입문 강의입니다.",
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-21T00:00:00.000Z",
    enrollmentEndAt: "2026-06-21T14:59:59.000Z",
    enrollmentCapacity: 50,
    enrollmentAppliedCount: 34,
    price: 69000,
    discountPrice: 49000,
    createdAt: "2026-05-20T00:00:00.000Z",
    purchaseCount: 1124,
    reviewCount: 148,
    avgRating: 4.7,
    likeCount: 358,
    instructor: { id: 9215, nickname: "UGC빌더", email: "roblox@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-21T00:00:00.000Z",
    includedFeatures: ["Lua 입문 노트", "라운드 시스템 예제", "상점 UI 템플릿", "공개 전 테스트 체크리스트"],
    relatedTopics: ["Roblox Studio", "Lua", "UGC", "Mini game", "Creator economy"],
    modules: [
      modulePlan("Roblox Studio 입문", [
        lessonPlan("첫 프로젝트와 인터페이스", "Explorer, Properties, Toolbox, Viewport를 실습 중심으로 익힙니다.", 18, ["roblox-first-project.pdf"]),
        lessonPlan("파트와 모델로 맵 만들기", "기본 블록, 재질, 충돌, 앵커를 사용해 미니게임 맵을 만듭니다.", 20),
        lessonPlan("스폰과 체크포인트", "플레이어가 시작하고 다시 살아나는 위치를 설정합니다.", 19),
        lessonPlan("프로젝트 폴더 정리", "Script, UI, Assets, RemoteEvents를 헷갈리지 않게 정리합니다.", 18),
      ]),
      modulePlan("Lua 스크립트 기초", [
        lessonPlan("변수, 함수, 조건문", "게임 점수와 상태를 예제로 Lua 기본 문법을 익힙니다.", 21),
        lessonPlan("이벤트와 터치 판정", "파트에 닿았을 때 점수, 데미지, 이동이 발생하게 합니다.", 21),
        lessonPlan("서버 스크립트와 로컬 스크립트", "어떤 로직을 서버에 두고 어떤 로직을 클라이언트에 둘지 구분합니다.", 22),
        lessonPlan("RemoteEvent로 UI 연결", "버튼 클릭과 서버 상태를 안전하게 주고받습니다.", 21),
      ]),
      modulePlan("라운드 미니게임 만들기", [
        lessonPlan("대기실과 라운드 타이머", "대기, 시작, 진행, 종료 상태를 가진 라운드 시스템을 만듭니다.", 22),
        lessonPlan("랜덤 맵 선택", "여러 미니맵 중 하나를 고르고 플레이어를 스폰합니다.", 21),
        lessonPlan("승리 조건과 점수", "마지막 생존자, 목표 달성, 시간 점수 같은 규칙을 구현합니다.", 22),
        lessonPlan("결과 화면", "라운드 종료 후 순위, 보상, 다시 시작 안내를 보여줍니다.", 20),
      ]),
      modulePlan("보상과 상점 UI", [
        lessonPlan("코인 보상 구조", "플레이 시간과 결과에 따라 보상을 지급합니다.", 20),
        lessonPlan("DataStore 저장", "코인, 구매 아이템, 설정 값을 저장하고 불러옵니다.", 22),
        lessonPlan("상점 UI 만들기", "아이템 목록, 가격, 구매 버튼, 보유 상태를 표시합니다.", 22),
        lessonPlan("꾸미기 아이템 적용", "장착한 이펙트나 색상이 플레이어에게 반영되게 합니다.", 20),
      ]),
      modulePlan("공개 전 테스트와 운영", [
        lessonPlan("친구 테스트와 버그 수집", "초기 플레이어에게 무엇을 물어봐야 하는지 테스트 문항을 만듭니다.", 18),
        lessonPlan("악용 가능한 로직 찾기", "클라이언트에서 조작하면 안 되는 값과 서버 검증 지점을 확인합니다.", 20),
        lessonPlan("썸네일과 설명 작성", "게임을 클릭하고 싶게 만드는 이미지와 짧은 설명을 준비합니다.", 18),
        lessonPlan("첫 업데이트 계획", "처음 공개 후 어떤 지표와 피드백을 보고 업데이트할지 정합니다.", 19, ["ugc-launch-checklist.xlsx"]),
      ]),
    ],
  }),
]

export const mockCourses: MockCourse[] = [
  {
    id: 101,
    title: "Next.js로 강의 거래소 만들기",
    slug: "nextjs-course-marketplace",
    shortDescription: "상품, 수강신청, 계좌입금 승인, SEO까지 웹 플랫폼의 뼈대를 완성합니다.",
    description: "웹 우선 강의 플랫폼을 직접 만들며 서비스 구조를 익힙니다. 판매 페이지, 모집 기간, 입금 확인 기반 수강 승인까지 실제 운영 흐름으로 배웁니다.",
    category: "웹 개발",
    level: "중급",
    languageCode: "ko",
    tags: ["Next.js", "Drizzle", "SEO"],
    seoKeywords: ["Next.js 강의", "강의 플랫폼", "Drizzle ORM", "SEO"],
    targetAudience: "직접 강의 플랫폼을 만들고 싶은 개발자와 1인 창업자",
    requirements: "React와 TypeScript 기초 지식",
    learningOutcomes: ["강의 목록과 상세 페이지 설계", "SEO 메타데이터 구성", "수강신청 흐름 이해"],
    metaTitle: "Next.js로 강의 거래소 만들기 | 링구스트",
    metaDescription: "Next.js, Drizzle, SEO 기반으로 강의 거래소의 핵심 구조를 만드는 강의입니다.",
    ogImageUrl: previewImages[0],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-10T00:00:00.000Z",
    enrollmentEndAt: "2026-06-05T14:59:59.000Z",
    enrollmentCapacity: 40,
    enrollmentAppliedCount: 27,
    price: 99000,
    discountPrice: 70000,
    imageUrl: previewImages[0],
    createdAt: "2026-05-01T00:00:00.000Z",
    purchaseCount: 1240,
    reviewCount: 186,
    avgRating: 4.88,
    likeCount: 342,
    instructor: { id: 9001, nickname: "링구스트랩", email: "studio@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-12T00:00:00.000Z",
    includedFeatures: ["실습용 Drizzle 스키마", "SEO 체크리스트", "운영 상태표 템플릿", "모바일/데스크톱 수강"],
    relatedTopics: ["Next.js", "Marketplace", "Drizzle ORM", "SEO", "Bank transfer approval"],
    sections: buildMockSections(101, [
      modulePlan("서비스 구조와 도메인 설계", [
        lessonPlan("강의 거래소의 핵심 사용자 흐름", "수강생, 판매자, 최고 관리자가 각각 어떤 화면과 상태를 가져야 하는지 정리합니다.", 16, ["domain-flow.pdf"]),
        lessonPlan("역할별 권한과 상태 전이", "수강 신청, 입금 대기, 승인, 수강 가능 상태를 상태 머신으로 나눕니다.", 18),
        lessonPlan("강의 상품이 가져야 할 필드", "가격, 할인, 모집 기간, 정원, SEO, 이미지 필드를 실제 등록 폼 기준으로 설계합니다.", 17),
        lessonPlan("웹 우선 구조와 앱 래핑 전략", "Next.js 웹을 먼저 완성하고 나중에 앱으로 감싸도 흔들리지 않는 경계를 잡습니다.", 15),
      ]),
      modulePlan("Drizzle ORM과 데이터 모델", [
        lessonPlan("Prisma에서 Drizzle로 옮길 때의 관점", "실무에서 자주 부딪히는 마이그레이션, 타입, 쿼리 문제를 비교합니다.", 18),
        lessonPlan("Lecture, Curriculum, Section 스키마", "강의, 섹션, 수업, 영상, 파일 관계를 Drizzle 테이블로 모델링합니다.", 20, ["schema-map.md"]),
        lessonPlan("수강 신청과 Purchase 권한 설계", "결제 대신 계좌입금 확인으로 권한을 여는 초기 운영 모델을 구현합니다.", 21),
        lessonPlan("판매자 계좌와 정산 데이터", "판매자가 직접 계좌를 등록하고 운영자가 나중에 정산할 수 있는 데이터를 남깁니다.", 17),
        lessonPlan("마이그레이션 운영 체크리스트", "컬럼 추가, 기본값, 배포 전후 순서를 안전하게 관리하는 기준을 세웁니다.", 16),
      ]),
      modulePlan("강의 목록과 상세 페이지", [
        lessonPlan("사진 중심 강의 카드 UI", "프리뷰 이미지, 모집 상태, 가격, 할인 배지를 소비자 마켓플레이스처럼 구성합니다.", 17),
        lessonPlan("시즌제 모집 상태 표시", "모집 전, 모집 중, 모집 완료, 신청 마감 상태를 한눈에 이해되게 만듭니다.", 18),
        lessonPlan("강의 상세 첫 화면 구성", "제목, 요약, 학습 결과, 추천 대상, 준비물을 전환 중심으로 배치합니다.", 19),
        lessonPlan("가격과 할인 정보 노출", "할인율이 주목되지만 과하게 시끄럽지 않은 가격 표시 패턴을 적용합니다.", 15),
        lessonPlan("리뷰와 좋아요의 초기 데이터 전략", "초기 서비스처럼 보이되 실제 운영과 충돌하지 않는 통계를 설계합니다.", 14),
      ]),
      modulePlan("SEO와 검색 노출", [
        lessonPlan("강의별 메타데이터 설계", "meta title, description, keywords, canonical URL을 강의 등록 데이터로 연결합니다.", 18, ["seo-fields.xlsx"]),
        lessonPlan("OG 이미지와 공유 카드", "1200px 계열 대표 이미지가 공유와 검색 결과에서 어떻게 쓰이는지 확인합니다.", 16),
        lessonPlan("sitemap.xml 자동 생성", "활성 강의가 검색엔진에 발견되도록 사이트맵 라우트를 구성합니다.", 18),
        lessonPlan("카테고리와 태그 구조", "검색 의도와 내부 탐색을 동시에 만족하는 태그 체계를 만듭니다.", 15),
      ]),
      modulePlan("계좌입금 수강 신청", [
        lessonPlan("수강 신청 API 만들기", "계좌입금 방식에서도 주문 금액, 신청자, 판매자 계좌 정보를 남깁니다.", 19),
        lessonPlan("입금 대기 화면과 안내 문구", "수강생이 어디로 입금해야 하는지, 언제 승인되는지 명확히 보여줍니다.", 16),
        lessonPlan("판매자 신청자 리스트", "판매자가 신청자와 입금 상태를 확인하고 승인할 수 있는 테이블을 만듭니다.", 18),
        lessonPlan("승인 시 Purchase 생성", "입금 확인 후 수강 권한을 부여하는 서버 액션과 예외 처리를 구현합니다.", 20),
        lessonPlan("취소와 중복 신청 처리", "같은 강의에 여러 번 신청했을 때 운영자가 헷갈리지 않도록 상태를 정리합니다.", 15),
      ]),
      modulePlan("판매자 스튜디오", [
        lessonPlan("강의 기본 정보 편집", "제목, 소개, 이미지, 가격, 모집 기간을 판매자가 관리하는 폼을 구성합니다.", 17),
        lessonPlan("커리큘럼 섹션과 수업 편집", "섹션 아래 여러 수업을 추가하고 공개 상태를 조절하는 UX를 만듭니다.", 19),
        lessonPlan("영상 업로드 전 운영 상태", "비디오가 없어도 커리큘럼과 판매 페이지는 먼저 완성될 수 있게 표시합니다.", 14),
        lessonPlan("판매자 대시보드 지표", "신청 수, 승인 수, 잔여 좌석, 예상 매출을 판매자가 빠르게 보게 합니다.", 16),
      ]),
      modulePlan("최고 관리자와 운영", [
        lessonPlan("전체 강의 승인 큐", "새 강의, 수정 요청, 인코딩 필요 여부를 운영자가 한 곳에서 봅니다.", 17),
        lessonPlan("수동 정산 준비 데이터", "강의별 신청 금액, 승인 수, 플랫폼 수수료를 정산 대기열로 모읍니다.", 18),
        lessonPlan("로컬 인코딩 작업 연결점", "배포 서버가 아니라 로컬 관리자 환경에서만 의미 있는 인코딩 실행 지점을 둡니다.", 16),
        lessonPlan("운영 로그와 문제 추적", "입금 승인, 권한 부여, 파일 처리 실패를 나중에 추적할 수 있게 기록합니다.", 15),
      ]),
      modulePlan("출시 전 검증", [
        lessonPlan("모바일/데스크톱 화면 QA", "카드, 상세, 신청, 대시보드가 화면 크기마다 깨지지 않는지 확인합니다.", 16),
        lessonPlan("SEO 결과물 점검", "메타 태그, OG 이미지, 사이트맵, canonical을 실제 HTML에서 확인합니다.", 15),
        lessonPlan("초기 운영 시나리오 리허설", "수강생 신청부터 판매자 승인, 관리자 정산 확인까지 전체 흐름을 한 번 돌립니다.", 18),
      ]),
    ]),
  },
  {
    id: 102,
    title: "HLS 스트리밍과 영상 운영",
    slug: "hls-video-operations",
    shortDescription: "ffmpeg, HLS, 자막, 더빙 트랙을 강의 서비스 흐름에 맞게 설계합니다.",
    description: "동영상 강의를 판매할 때 필요한 HLS 운영 전략을 다룹니다. 로컬 인코딩 승인 플로우를 기준으로 설명합니다.",
    category: "미디어",
    level: "고급",
    languageCode: "ko",
    tags: ["HLS", "FFmpeg", "Caption"],
    seoKeywords: ["HLS 강의", "FFmpeg", "영상 인코딩", "자막"],
    targetAudience: "영상 기반 교육 서비스를 운영하려는 개발자와 강의 판매자",
    requirements: "기본적인 파일 업로드와 웹 비디오 개념",
    learningOutcomes: ["HLS 변환 흐름 이해", "자막 트랙 운영", "로컬 인코딩 승인 방식 설계"],
    metaTitle: "HLS 스트리밍과 영상 운영 | 링구스트",
    metaDescription: "강의 플랫폼에서 HLS, 자막, 더빙 트랙을 운영하는 방법을 다루는 강의입니다.",
    ogImageUrl: previewImages[1],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-01T00:00:00.000Z",
    enrollmentEndAt: "2026-05-28T14:59:59.000Z",
    enrollmentCapacity: 24,
    enrollmentAppliedCount: 24,
    price: 129000,
    discountPrice: null,
    imageUrl: previewImages[1],
    createdAt: "2026-05-02T00:00:00.000Z",
    purchaseCount: 520,
    reviewCount: 73,
    avgRating: 4.91,
    likeCount: 189,
    instructor: { id: 9002, nickname: "스트림마스터", email: "stream@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-10T00:00:00.000Z",
    includedFeatures: ["HLS 인코딩 스크립트", "자막/VTT 템플릿", "로컬 승인 운영 가이드", "재생 QA 체크리스트"],
    relatedTopics: ["HLS", "FFmpeg", "VTT captions", "Dubbing", "Video QA"],
    sections: buildMockSections(102, [
      modulePlan("스트리밍 운영의 기본기", [
        lessonPlan("강의 서비스에서 HLS가 필요한 이유", "다운로드형 영상과 스트리밍형 영상의 운영 차이를 비용, 보안, UX 관점으로 봅니다.", 20, ["hls-decision-guide.pdf"]),
        lessonPlan("적응형 스트리밍 구조 읽기", "master playlist, variant playlist, segment 파일이 어떤 역할을 하는지 해부합니다.", 23),
        lessonPlan("브라우저별 재생 전략", "Safari 네이티브 HLS와 Chrome hls.js 적용 방식을 나눠 설계합니다.", 19),
        lessonPlan("원본 파일 보관과 공개 파일 분리", "업로드 원본, 인코딩 결과물, 썸네일, 자막 파일의 저장 위치를 구분합니다.", 18),
      ]),
      modulePlan("FFmpeg 인코딩 파이프라인", [
        lessonPlan("원본 영상 분석하기", "해상도, 프레임레이트, 오디오 채널, 비트레이트를 인코딩 전에 확인합니다.", 22),
        lessonPlan("해상도 ladder 구성", "강의 영상에 맞는 1080p, 720p, 480p ladder를 만들고 과도한 변환을 피합니다.", 27),
        lessonPlan("segment 길이와 keyframe 설정", "탐색 속도와 파일 수 사이의 균형을 잡는 segment 전략을 적용합니다.", 25),
        lessonPlan("오디오 설정과 음량 정규화", "강의에서 듣기 좋은 음량과 압축 설정을 ffmpeg 옵션으로 정리합니다.", 21),
        lessonPlan("인코딩 실패 로그 읽기", "코덱 불일치, 손상 파일, 권한 문제를 로그에서 빠르게 분류합니다.", 20),
      ]),
      modulePlan("로컬 승인형 인코딩", [
        lessonPlan("왜 인코딩 서버를 당장 두지 않는가", "초기 운영에서 서버 비용을 줄이고 관리자 승인 흐름에 인코딩을 붙이는 이유를 설명합니다.", 19),
        lessonPlan("Next.js API와 로컬 실행 경계", "배포 서버에서도 존재하지만 실제 동작은 로컬 개발 환경에서만 허용하는 구조를 만듭니다.", 24),
        lessonPlan("관리자 승인 버튼의 작업 순서", "승인, 인코딩, 업로드, 상태 업데이트가 꼬이지 않도록 순서를 설계합니다.", 22),
        lessonPlan("긴 작업 중 UI 상태 처리", "인코딩 중, 실패, 재시도, 완료 상태를 관리자 페이지에서 보여줍니다.", 20),
        lessonPlan("R2/S3 업로드 키 규칙", "강의와 수업 id를 기준으로 HLS 파일 경로를 예측 가능하게 만듭니다.", 19, ["storage-key-rules.md"]),
      ]),
      modulePlan("자막과 다국어 트랙", [
        lessonPlan("VTT 자막 파일 구조", "시간 코드, cue, 언어 라벨을 브라우저 플레이어에 맞게 구성합니다.", 20),
        lessonPlan("영상 내 자막과 별도 자막의 충돌", "이미 자막이 박힌 영상에 별도 자막을 강제로 켜지 않도록 UX를 정합니다.", 18),
        lessonPlan("다국어 자막 등록 폼", "판매자가 한국어, 영어, 일본어 자막을 직접 등록할 수 있는 필드를 설계합니다.", 21),
        lessonPlan("자막 품질 검수 체크", "싱크, 줄 길이, 특수문자, 모바일 가독성을 검수하는 기준을 만듭니다.", 19),
      ]),
      modulePlan("플레이어 UX와 접근 제어", [
        lessonPlan("무료 공개와 유료 잠금의 차이", "무료 공개가 아닌 수업은 수강 승인 전 재생 버튼이 나타나지 않도록 합니다.", 20),
        lessonPlan("수강 권한 검증 위치", "프론트 숨김만으로 끝내지 않고 API에서 구매 권한을 확인하는 흐름을 설계합니다.", 22),
        lessonPlan("이어보기와 진도 저장", "나중에 확장할 수 있도록 플레이어 이벤트와 진도 저장 지점을 잡습니다.", 19),
        lessonPlan("모바일 재생 제약", "자동재생, inline playback, 전체화면 전환 같은 모바일 제약을 정리합니다.", 18),
      ]),
      modulePlan("운영 비용과 스토리지", [
        lessonPlan("S3, R2, Cloudflare Stream 비교", "스토리지, egress, 인코딩 비용을 초기 강의 플랫폼 관점에서 비교합니다.", 25),
        lessonPlan("R2로 옮길 때 바뀌는 것", "SDK, presigned URL, public bucket, CDN 캐시 정책의 차이를 봅니다.", 22),
        lessonPlan("Cloudflare Stream을 쓰는 경우", "인코딩 서버를 없앨 수 있는 대신 발생하는 과금과 제약을 따져봅니다.", 21),
        lessonPlan("저비용 운영 의사결정표", "트래픽이 적은 초기, 강의 수가 늘어난 중기, 규모화 이후의 선택지를 나눕니다.", 20),
      ]),
      modulePlan("릴리즈 전 영상 QA", [
        lessonPlan("데스크톱 재생 테스트", "Chrome, Safari, Firefox에서 manifest 로딩과 seek 동작을 확인합니다.", 18),
        lessonPlan("모바일 재생 테스트", "iOS Safari와 Android Chrome에서 UI와 오디오 동작을 확인합니다.", 18),
        lessonPlan("CORS와 MIME type 문제", "m3u8, ts, vtt 파일의 Content-Type과 CORS 오류를 해결합니다.", 21),
        lessonPlan("출시 전 최종 체크리스트", "샘플 영상, 썸네일, 자막, 권한, 상태 값을 한 번에 점검합니다.", 17, ["video-release-checklist.pdf"]),
      ]),
      modulePlan("실전 운영 프로젝트", [
        lessonPlan("샘플 원본을 인코딩 큐에 넣기", "관리자 승인 시점에 원본 영상이 어떤 순서로 처리되는지 프로젝트처럼 따라갑니다.", 24),
        lessonPlan("HLS 결과물 검수하기", "생성된 manifest, variant, segment 파일을 열어보고 잘못된 경로를 찾습니다.", 25),
        lessonPlan("자막과 썸네일 함께 배포하기", "영상 파일만이 아니라 자막, 썸네일, 공개 상태까지 같이 점검합니다.", 23),
        lessonPlan("실패한 인코딩 재시도하기", "실패 상태를 남기고 원인을 수정한 뒤 다시 인코딩하는 운영 절차를 연습합니다.", 24),
        lessonPlan("운영 비용 보고서 만들기", "스토리지, 전송량, 인코딩 시간 기준으로 한 달 운영 비용을 추정합니다.", 23, ["video-cost-report.xlsx"]),
      ]),
    ]),
  },
  {
    id: 103,
    title: "AI 시대 판매되는 강의 기획법",
    slug: "ai-course-planning",
    shortDescription: "검색되는 커리큘럼, 전환되는 상세 페이지, 완주율 높은 수업 설계.",
    description: "강의 판매자가 콘텐츠를 시장에 맞게 설계하는 법을 배웁니다. 검색 의도와 공개 영상 구성, 판매 페이지 카피까지 한 번에 정리합니다.",
    category: "크리에이터",
    level: "입문",
    languageCode: "ko",
    tags: ["기획", "마케팅", "커리큘럼"],
    seoKeywords: ["강의 기획", "온라인 강의 판매", "커리큘럼 설계", "AI 강의"],
    targetAudience: "첫 강의를 준비하는 크리에이터와 전문가",
    requirements: "팔고 싶은 주제와 간단한 촬영 도구",
    learningOutcomes: ["판매되는 강의 주제 선정", "검색 의도 기반 목차 구성", "상세 페이지 전환 포인트 설계"],
    metaTitle: "AI 시대 판매되는 강의 기획법 | 링구스트",
    metaDescription: "검색되는 커리큘럼과 전환되는 상세 페이지를 설계하는 강의 기획 강의입니다.",
    ogImageUrl: previewImages[2],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-08T00:00:00.000Z",
    enrollmentEndAt: "2026-06-12T14:59:59.000Z",
    enrollmentCapacity: 60,
    enrollmentAppliedCount: 41,
    price: 59000,
    discountPrice: 42000,
    imageUrl: previewImages[2],
    createdAt: "2026-05-03T00:00:00.000Z",
    purchaseCount: 870,
    reviewCount: 92,
    avgRating: 4.74,
    likeCount: 277,
    instructor: { id: 9003, nickname: "콘텐츠빌더", email: "creator@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-09T00:00:00.000Z",
    includedFeatures: ["강의 기획 워크시트", "상세페이지 카피 예시", "커리큘럼 리뷰 체크리스트", "런칭 메시지 템플릿"],
    relatedTopics: ["Course planning", "Creator business", "AI workflow", "Landing copy", "Curriculum design"],
    sections: buildMockSections(103, [
      modulePlan("팔리는 주제 찾기", [
        lessonPlan("주제 후보를 시장 언어로 바꾸기", "내가 하고 싶은 말이 아니라 수강생이 검색하는 문제로 주제를 다시 표현합니다.", 15, ["topic-scorecard.pdf"]),
        lessonPlan("전문성과 수요의 교차점", "내가 잘 아는 것과 사람들이 돈을 낼 만큼 아픈 지점을 겹쳐 봅니다.", 16),
        lessonPlan("경쟁 강의 빠르게 분석하기", "비슷한 강의의 제목, 가격, 목차, 리뷰를 보고 빈틈을 찾습니다.", 14),
        lessonPlan("첫 시즌에 팔 크기 정하기", "처음부터 대형 강의가 아니라 완주 가능한 범위로 상품을 좁힙니다.", 15),
      ]),
      modulePlan("수강생 약속 설계", [
        lessonPlan("결과 중심 한 문장 만들기", "수강생이 강의 후 무엇을 할 수 있게 되는지 한 문장으로 압축합니다.", 16),
        lessonPlan("추천 대상과 비추천 대상", "누구에게 맞고 누구에게 맞지 않는지 명확히 적어 신뢰를 만듭니다.", 14),
        lessonPlan("준비물과 전제 지식 정리", "초보자가 들어도 되는지, 어떤 경험이 필요한지 오해 없이 안내합니다.", 13),
        lessonPlan("학습 결과를 체크리스트로 바꾸기", "상세 페이지의 배우게 되는 항목을 실제 커리큘럼과 연결합니다.", 16),
      ]),
      modulePlan("커리큘럼 상품화", [
        lessonPlan("섹션 단위로 여정 만들기", "수업 나열이 아니라 문제 인식, 실습, 결과물 순서로 섹션을 만듭니다.", 18, ["curriculum-ladder.xlsx"]),
        lessonPlan("수업 제목을 구매 이유로 쓰기", "기능명이나 도구명보다 수강생이 얻는 결과 중심으로 제목을 바꿉니다.", 15),
        lessonPlan("짧은 수업과 긴 수업의 배치", "몰입이 깨지지 않도록 설명, 실습, 정리 수업의 길이를 조절합니다.", 16),
        lessonPlan("자료와 과제를 어디에 붙일까", "워크시트, 예제, 체크리스트를 커리큘럼 안에 자연스럽게 배치합니다.", 14),
      ]),
      modulePlan("상세 페이지 카피", [
        lessonPlan("첫 화면에서 신뢰 만들기", "제목, 부제, 이미지, 가격, 신청 방식이 동시에 설득하도록 구성합니다.", 16),
        lessonPlan("학습 결과 문장 다듬기", "흔한 추상 문장을 실제 행동으로 바꾸어 작성합니다.", 14),
        lessonPlan("가격 방어 문구 만들기", "왜 이 가격인지, 어떤 결과물을 얻는지 상세 페이지 안에서 설명합니다.", 15),
        lessonPlan("FAQ와 반박 처리", "수강생이 결제 전에 망설이는 질문을 미리 정리합니다.", 15),
      ]),
      modulePlan("AI를 활용한 제작 흐름", [
        lessonPlan("AI로 목차 초안 만들기", "AI를 브레인스토밍 도구로 쓰되 그대로 복붙하지 않는 기준을 세웁니다.", 15),
        lessonPlan("대본과 예시 생성하기", "수업별 예시, 설명 순서, 연습 문제를 빠르게 뽑아 다듬습니다.", 16),
        lessonPlan("상세 페이지 초안 생성", "AI가 만든 초안을 브랜드 톤과 실제 운영 정보에 맞게 교정합니다.", 14),
        lessonPlan("품질 검수 루틴", "AI가 만든 내용에서 과장, 허위, 빈약한 설명을 걸러냅니다.", 13),
      ]),
      modulePlan("첫 모집 운영", [
        lessonPlan("시즌 모집 일정 짜기", "신청 시작, 마감, 입금 확인, 첫 강의 오픈 일정을 정합니다.", 15),
        lessonPlan("초기 수강생에게 보내는 안내", "계좌입금 방식에서 필요한 안내 메시지와 확인 절차를 만듭니다.", 14),
        lessonPlan("리뷰와 피드백 받는 흐름", "첫 시즌 종료 후 다음 시즌 상세 페이지를 개선할 피드백을 모읍니다.", 15),
        lessonPlan("다음 강의로 확장하기", "첫 강의의 결과를 보고 후속 강의나 심화반을 설계합니다.", 13),
      ]),
    ]),
  },
  {
    id: 104,
    title: "수강생이 끝까지 보는 강의 편집",
    slug: "course-editing-retention",
    shortDescription: "긴 영상보다 오래 남는 리듬, 챕터, 대표 이미지를 설계합니다.",
    description: "촬영 이후 실제 판매 페이지에 올라가는 결과물을 다듬습니다.",
    category: "디자인",
    level: "입문",
    languageCode: "ko",
    tags: ["편집", "썸네일", "완주율"],
    seoKeywords: ["강의 편집", "온라인 강의 썸네일", "완주율"],
    targetAudience: "강의 영상을 더 보기 좋게 만들고 싶은 판매자",
    requirements: "기본적인 영상 편집 툴",
    learningOutcomes: ["챕터 구조화", "대표 이미지 구성", "완주율을 높이는 편집 리듬"],
    metaTitle: "수강생이 끝까지 보는 강의 편집 | 링구스트",
    metaDescription: "강의 영상의 리듬, 챕터, 대표 이미지를 설계하는 강의입니다.",
    ogImageUrl: previewImages[3],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-04-15T00:00:00.000Z",
    enrollmentEndAt: "2026-05-12T14:59:59.000Z",
    enrollmentCapacity: 30,
    enrollmentAppliedCount: 22,
    price: 79000,
    discountPrice: 59000,
    imageUrl: previewImages[3],
    createdAt: "2026-05-04T00:00:00.000Z",
    purchaseCount: 438,
    reviewCount: 61,
    avgRating: 4.82,
    likeCount: 164,
    instructor: { id: 9004, nickname: "컷앤런", email: "edit@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-08T00:00:00.000Z",
    includedFeatures: ["편집 리듬 체크리스트", "썸네일 템플릿", "챕터 구성 예시", "업로드 전 QA 시트"],
    relatedTopics: ["Video editing", "Retention", "Thumbnails", "Chapter design"],
    sections: buildMockSections(104, [
      modulePlan("강의 편집 기준 잡기", [
        lessonPlan("완주율을 떨어뜨리는 장면 찾기", "편집 전에 지루함, 반복, 설명 누락 구간을 표시하는 기준을 만듭니다.", 17, ["retention-audit.pdf"]),
        lessonPlan("강의 영상의 호흡 설계", "말의 속도, 침묵, 화면 전환, 줌인을 어디에 넣을지 정합니다.", 18),
        lessonPlan("수업 길이와 챕터 분할", "하나의 긴 영상을 여러 수업으로 나눌 때 기준을 세웁니다.", 16),
        lessonPlan("수강생 관점으로 다시 보기", "편집자가 아니라 처음 배우는 사람의 시선으로 흐름을 점검합니다.", 15),
      ]),
      modulePlan("컷 편집과 화면 리듬", [
        lessonPlan("불필요한 앞뒤 여백 정리", "녹화 시작과 종료의 어색한 구간을 자연스럽게 제거합니다.", 14),
        lessonPlan("설명 중 멈춤과 반복 처리", "강의자의 실수, 반복 설명, 생각하는 시간을 깔끔하게 다듬습니다.", 17),
        lessonPlan("화면 확대와 강조 컷", "코드, 문서, 슬라이드에서 집중해야 할 부분을 확대하는 타이밍을 배웁니다.", 18),
        lessonPlan("B-roll과 보조 화면 사용", "실습 화면만으로 지루할 때 보조 화면을 넣는 원칙을 정합니다.", 16),
      ]),
      modulePlan("오디오와 자막 정리", [
        lessonPlan("강의 오디오 노이즈 제거", "배경 소음, 클릭음, 숨소리, 음량 차이를 기본 수준에서 정리합니다.", 18),
        lessonPlan("말소리 음량 표준화", "수업마다 음량이 달라지지 않도록 기준을 맞춥니다.", 16),
        lessonPlan("자막이 필요한 구간 고르기", "전체 자막, 부분 자막, 화면 내 텍스트의 역할을 구분합니다.", 17),
        lessonPlan("영상 내 자막과 별도 자막", "박힌 자막과 선택 자막이 충돌하지 않도록 운영 기준을 세웁니다.", 15),
      ]),
      modulePlan("썸네일과 프리뷰 이미지", [
        lessonPlan("강의 대표 이미지의 역할", "클릭을 부르는 이미지가 아니라 내용을 신뢰시키는 이미지를 만듭니다.", 17),
        lessonPlan("할인 배지와 정보 밀도", "가격 할인은 보이게, 전체 이미지는 시끄럽지 않게 구성합니다.", 16),
        lessonPlan("수업별 대표 프레임 고르기", "영상 중 수업 내용을 잘 보여주는 프레임을 추출합니다.", 15),
        lessonPlan("이미지 비율과 크롭 QA", "1200x781 비율에서 텍스트와 핵심 오브젝트가 잘리지 않는지 확인합니다.", 16, ["thumbnail-safe-area.png"]),
      ]),
      modulePlan("학습 흐름을 살리는 챕터", [
        lessonPlan("챕터명은 결과 중심으로", "도구명보다 수강생이 얻는 결과를 챕터명에 반영합니다.", 15),
        lessonPlan("복습 가능한 구조 만들기", "수강생이 나중에 필요한 수업만 다시 찾을 수 있게 목차를 정리합니다.", 16),
        lessonPlan("실습 전 설명과 실습 후 정리", "실습만 길게 이어지지 않도록 앞뒤 요약 수업을 배치합니다.", 17),
        lessonPlan("자료 다운로드 위치 잡기", "편집 파일, 체크리스트, 예제 자료가 필요한 수업에 붙도록 구성합니다.", 14),
      ]),
      modulePlan("업로드 전 품질 검수", [
        lessonPlan("화질과 글자 가독성 확인", "코드, 문서, 슬라이드 글자가 모바일에서도 읽히는지 확인합니다.", 18),
        lessonPlan("싱크와 끊김 점검", "오디오 싱크, 화면 멈춤, 잘못 잘린 컷을 찾는 루틴을 만듭니다.", 16),
        lessonPlan("HLS 변환을 위한 export 설정", "후속 인코딩이 안정적으로 되도록 원본 파일 설정을 맞춥니다.", 18),
        lessonPlan("출시 전 최종 리스트", "썸네일, 영상, 자막, 자료, 설명 문구를 한 번에 검수합니다.", 15, ["publish-qa-sheet.xlsx"]),
      ]),
      modulePlan("실전 편집 프로젝트", [
        lessonPlan("원본 강의를 편집 계획으로 바꾸기", "긴 녹화본을 보고 어느 지점을 자르고 나눌지 편집 계획표를 만듭니다.", 19),
        lessonPlan("한 수업을 완성본으로 만들기", "컷 편집, 오디오 보정, 자막, 대표 프레임 추출을 한 번에 진행합니다.", 22),
        lessonPlan("섹션 전체 톤 맞추기", "여러 수업 사이의 소리, 화면 크기, 시작/종료 리듬을 통일합니다.", 20),
        lessonPlan("판매 페이지용 이미지 뽑기", "커리큘럼과 상세 페이지에 쓸 대표 프레임을 골라 저장합니다.", 19),
      ]),
    ]),
  },
  {
    id: 105,
    title: "강의 판매자를 위한 SEO 실전",
    slug: "course-seo-practice",
    shortDescription: "태그, 메타 타이틀, 사이트맵, 검색 의도를 강의 등록 폼에 녹입니다.",
    description: "강의가 검색 결과에 남도록 구조화하는 방법을 다룹니다.",
    category: "비즈니스",
    level: "중급",
    languageCode: "ko",
    tags: ["SEO", "검색", "콘텐츠"],
    seoKeywords: ["강의 SEO", "메타 타이틀", "사이트맵", "콘텐츠 SEO"],
    targetAudience: "강의를 검색 결과에 노출시키고 싶은 판매자",
    requirements: "등록할 강의 주제와 키워드 후보",
    learningOutcomes: ["SEO 필드 작성", "검색 의도 매칭", "강의 상세 구조화"],
    metaTitle: "강의 판매자를 위한 SEO 실전 | 링구스트",
    metaDescription: "강의 등록 시 필요한 SEO 필드를 실전적으로 작성하는 강의입니다.",
    ogImageUrl: previewImages[4],
    canonicalUrl: null,
    enrollmentOpen: false,
    enrollmentStartAt: "2026-06-20T00:00:00.000Z",
    enrollmentEndAt: "2026-07-05T14:59:59.000Z",
    enrollmentCapacity: 35,
    enrollmentAppliedCount: 0,
    price: 89000,
    discountPrice: null,
    imageUrl: previewImages[4],
    createdAt: "2026-05-05T00:00:00.000Z",
    purchaseCount: 312,
    reviewCount: 44,
    avgRating: 4.79,
    likeCount: 121,
    instructor: { id: 9005, nickname: "검색설계자", email: "seo@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-07T00:00:00.000Z",
    includedFeatures: ["SEO 필드 템플릿", "사이트맵 점검표", "검색 의도 리서치 예시", "검색 노출 QA 리스트"],
    relatedTopics: ["SEO", "Metadata", "Sitemap", "Search intent", "Course landing pages"],
    sections: buildMockSections(105, [
      modulePlan("검색 의도 리서치", [
        lessonPlan("강의 주제를 검색어로 번역하기", "판매자가 쓰는 말과 수강생이 검색하는 말의 차이를 찾습니다.", 18, ["intent-map-template.xlsx"]),
        lessonPlan("상업적 의도와 정보성 의도", "바로 신청할 사람과 정보를 찾는 사람을 나눠 페이지 문구를 설계합니다.", 20),
        lessonPlan("경쟁 페이지 SERP 읽기", "검색 결과 상위 페이지의 제목, 설명, 구조를 분석합니다.", 19),
        lessonPlan("키워드 우선순위 정하기", "검색량보다 전환 가능성과 강의 적합도를 기준으로 우선순위를 정합니다.", 18),
      ]),
      modulePlan("강의 등록 SEO 필드", [
        lessonPlan("meta title 작성 공식", "강의명, 결과, 대상, 브랜드를 자연스럽게 포함하는 제목을 만듭니다.", 18),
        lessonPlan("meta description 작성", "검색 결과에서 클릭 이유가 되는 요약 문구를 작성합니다.", 17),
        lessonPlan("seoKeywords와 tags의 역할", "검색엔진용 키워드와 사용자 탐색용 태그를 구분합니다.", 16),
        lessonPlan("canonical URL과 slug", "중복 페이지를 피하고 공유하기 좋은 URL 구조를 잡습니다.", 18),
      ]),
      modulePlan("상세 페이지 구조화", [
        lessonPlan("H1과 첫 문단의 책임", "검색엔진과 수강생이 동시에 이해하는 첫 화면 문장을 만듭니다.", 18),
        lessonPlan("학습 결과를 구조화 데이터로 연결", "배우게 되는 것, 준비물, 추천 대상을 상세 페이지 데이터로 관리합니다.", 19),
        lessonPlan("커리큘럼 텍스트 SEO", "각 섹션과 수업 제목이 검색 의도를 보강하도록 작성합니다.", 20),
        lessonPlan("FAQ와 리뷰 영역 설계", "질문과 후기 콘텐츠가 검색 노출에 도움 되도록 배치합니다.", 17),
      ]),
      modulePlan("이미지와 공유 최적화", [
        lessonPlan("OG 이미지 기준", "1200px 대표 이미지가 공유 카드에서 잘 보이는지 확인합니다.", 15),
        lessonPlan("이미지 alt와 파일 경로", "대표 이미지와 본문 이미지의 설명, 파일명, 경로를 정리합니다.", 17),
        lessonPlan("할인 문구와 이미지 텍스트", "이미지 안 문구가 검색 노출과 브랜드 신뢰를 해치지 않도록 구성합니다.", 16),
        lessonPlan("SNS 공유 미리보기 확인", "카카오, X, 페이스북 공유 카드에서 제목과 이미지가 맞는지 봅니다.", 15),
      ]),
      modulePlan("사이트맵과 인덱싱", [
        lessonPlan("sitemap.xml 라우트 구성", "활성 강의와 공개 페이지가 자동으로 사이트맵에 들어가도록 만듭니다.", 20, ["sitemap-checklist.md"]),
        lessonPlan("robots와 noindex 기준", "관리자, 결제, 비공개 페이지를 검색에서 제외하는 기준을 세웁니다.", 18),
        lessonPlan("검색엔진 발견 속도 높이기", "새 강의를 공개한 뒤 인덱싱 요청과 내부 링크를 점검합니다.", 17),
        lessonPlan("삭제와 비공개 페이지 처리", "마감되거나 숨긴 강의가 검색 결과에 남는 문제를 관리합니다.", 16),
      ]),
      modulePlan("성과 측정", [
        lessonPlan("검색 노출과 클릭 지표", "노출, 클릭, CTR, 평균 순위를 보고 어떤 문구를 바꿀지 판단합니다.", 18),
        lessonPlan("상세 페이지 전환 추적", "검색 유입이 실제 수강 신청으로 이어지는지 이벤트를 설계합니다.", 18),
        lessonPlan("태그별 성과 보기", "어떤 카테고리와 태그가 신청으로 이어지는지 운영자 화면에 반영합니다.", 16),
        lessonPlan("다음 시즌 SEO 개선", "모집이 끝난 뒤 제목, 커리큘럼, FAQ를 다음 시즌에 맞게 갱신합니다.", 17),
      ]),
      modulePlan("실전 등록 리허설", [
        lessonPlan("샘플 강의 SEO 작성", "하나의 강의를 골라 실제 등록 폼을 처음부터 끝까지 채웁니다.", 20),
        lessonPlan("검색 결과 스니펫 검수", "메타 정보와 OG 카드가 실제 HTML에 반영됐는지 확인합니다.", 16),
        lessonPlan("출시 전 SEO QA", "사이트맵, canonical, 이미지, 제목, 설명을 체크리스트로 검수합니다.", 17, ["seo-release-qa.pdf"]),
      ]),
      modulePlan("콘텐츠 개선 운영", [
        lessonPlan("검색 유입 없는 강의 진단", "노출이 없을 때 제목, 태그, 상세 설명, 내부 링크 중 어디부터 볼지 정합니다.", 20),
        lessonPlan("클릭은 있는데 신청이 없는 페이지", "검색 의도는 맞지만 상세 페이지 설득이 약한 경우를 개선합니다.", 21),
        lessonPlan("모집 종료 후 SEO 유지", "모집이 끝난 강의를 삭제하지 않고 다음 시즌 신청으로 연결하는 방법을 봅니다.", 19),
        lessonPlan("분기별 키워드 리프레시", "트렌드와 경쟁 강의가 바뀌었을 때 메타데이터를 갱신하는 루틴을 만듭니다.", 20),
      ]),
    ]),
  },
  {
    id: 106,
    title: "자동 더빙과 다국어 강의 운영",
    slug: "ai-dubbing-course-operations",
    shortDescription: "ElevenLabs 기반 더빙을 수업 단위로 승인하고 운영하는 실전 플로우.",
    description: "다국어 오디오 트랙을 운영하고 관리하는 방식을 배웁니다.",
    category: "AI",
    level: "고급",
    languageCode: "ko",
    tags: ["AI", "더빙", "글로벌"],
    seoKeywords: ["AI 더빙", "ElevenLabs", "다국어 강의"],
    targetAudience: "국내 강의를 해외로 확장하고 싶은 판매자",
    requirements: "원본 강의 영상과 대본",
    learningOutcomes: ["더빙 승인 흐름", "언어 트랙 관리", "자막과 음성의 역할 분리"],
    metaTitle: "자동 더빙과 다국어 강의 운영 | 링구스트",
    metaDescription: "ElevenLabs 기반 자동 더빙과 다국어 강의 운영 흐름을 보는 강의입니다.",
    ogImageUrl: previewImages[5],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-18T00:00:00.000Z",
    enrollmentEndAt: "2026-06-30T14:59:59.000Z",
    enrollmentCapacity: 18,
    enrollmentAppliedCount: 6,
    price: 119000,
    discountPrice: 99000,
    imageUrl: previewImages[5],
    createdAt: "2026-05-06T00:00:00.000Z",
    purchaseCount: 284,
    reviewCount: 39,
    avgRating: 4.86,
    likeCount: 118,
    instructor: { id: 9006, nickname: "보이스빌더", email: "voice@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-11T00:00:00.000Z",
    includedFeatures: ["ElevenLabs 운영 체크리스트", "다국어 QA 시트", "자막/더빙 분리 가이드", "오디오 트랙 운영표"],
    relatedTopics: ["AI dubbing", "ElevenLabs", "Captions", "Localization", "Audio QA"],
    sections: buildMockSections(106, [
      modulePlan("다국어 운영 전략", [
        lessonPlan("모든 수업을 더빙하지 않는 기준", "비용 대비 효과가 높은 수업과 원어 그대로 둘 수업을 구분합니다.", 22, ["dubbing-priority-matrix.pdf"]),
        lessonPlan("언어별 출시 우선순위", "영어, 일본어, 중국어 등 목표 시장에 따라 어떤 언어부터 열지 정합니다.", 20),
        lessonPlan("자막, 더빙, 원본 음성의 역할", "자막만 필요한 경우와 더빙까지 필요한 경우를 운영 기준으로 나눕니다.", 21),
        lessonPlan("승인형 자동화 흐름", "AI 결과물을 바로 공개하지 않고 관리자 검수 후 반영하는 구조를 잡습니다.", 20),
      ]),
      modulePlan("원본 오디오 준비", [
        lessonPlan("영상에서 음성 추출하기", "원본 mp4에서 오디오를 분리하고 후처리 가능한 포맷으로 만듭니다.", 22),
        lessonPlan("음량 정규화와 노이즈 정리", "더빙 품질을 높이기 위해 원본 음성의 노이즈와 음량을 정리합니다.", 24),
        lessonPlan("문장 단위로 스크립트 나누기", "번역과 더빙이 자연스럽게 되도록 긴 문장을 쪼갭니다.", 21),
        lessonPlan("발음이 어려운 고유명사 처리", "서비스명, 사람 이름, 기술 용어의 발음 힌트를 준비합니다.", 19),
      ]),
      modulePlan("ElevenLabs API 연결", [
        lessonPlan("API 키와 프로젝트 설정", "환경변수, 사용량 제한, 실패 시 재시도 기준을 정합니다.", 20),
        lessonPlan("음성 모델과 보이스 선택", "강의 톤에 맞는 보이스를 선택하고 언어별 차이를 확인합니다.", 23),
        lessonPlan("긴 수업을 안전하게 나누기", "API 제한과 비용을 고려해 수업 오디오를 적절히 분할합니다.", 23),
        lessonPlan("결과 파일 저장 규칙", "언어, 수업, 버전을 포함한 오디오 파일 경로를 표준화합니다.", 20),
      ]),
      modulePlan("번역과 자막", [
        lessonPlan("직역이 망치는 강의 문장", "기술 강의에서 어색한 직역을 줄이고 의미 중심으로 다듬습니다.", 20),
        lessonPlan("VTT 자막 자동 생성", "번역된 스크립트를 시간 코드가 있는 자막 파일로 변환합니다.", 22),
        lessonPlan("자막과 음성 싱크 맞추기", "더빙된 음성과 자막이 크게 어긋나지 않도록 검수합니다.", 21),
        lessonPlan("언어별 기본 자막 정책", "사용자 언어와 영상 언어에 따라 기본 표시 여부를 결정합니다.", 18),
      ]),
      modulePlan("HLS 오디오 트랙 설계", [
        lessonPlan("대체 오디오 트랙 구조", "HLS에서 언어별 오디오 트랙을 어떻게 참조하는지 살펴봅니다.", 24),
        lessonPlan("플레이어 언어 선택 UI", "수강생이 음성과 자막을 따로 선택하는 UI를 설계합니다.", 20),
        lessonPlan("마지막 선택 언어 저장", "사용자가 선택한 언어를 다음 수업에서도 유지하도록 설계합니다.", 18),
        lessonPlan("트랙 누락과 fallback 처리", "특정 언어 파일이 없을 때 원본 음성으로 안전하게 돌아가게 합니다.", 21),
      ]),
      modulePlan("품질 검수와 승인", [
        lessonPlan("AI 더빙 품질 체크리스트", "발음, 억양, 누락 문장, 어색한 감정을 검수합니다.", 20, ["voice-qa-sheet.xlsx"]),
        lessonPlan("강의자가 직접 들어야 하는 구간", "AI가 자주 틀리는 핵심 개념과 브랜드명을 우선 검수합니다.", 19),
        lessonPlan("승인, 반려, 재생성 상태", "더빙 트랙별 상태를 관리자 화면에서 관리합니다.", 21),
        lessonPlan("공개 전 최종 재생 테스트", "언어 전환, 자막 싱크, 모바일 재생을 한 번에 확인합니다.", 20),
      ]),
      modulePlan("비용과 운영 정책", [
        lessonPlan("분당 비용 계산하기", "강의 길이, 언어 수, 재생성 횟수에 따른 비용을 추정합니다.", 21),
        lessonPlan("무료 강의와 유료 강의의 더빙 기준", "모든 콘텐츠를 더빙하지 않고 매출 가능성이 있는 강의부터 처리합니다.", 18),
        lessonPlan("강의 판매자에게 보여줄 상태", "더빙 요청, 처리 중, 검수 필요, 공개 완료를 판매자에게 설명합니다.", 18),
        lessonPlan("글로벌 출시 순서 짜기", "한 번에 전 세계 공개가 아니라 시장별로 작은 출시를 계획합니다.", 19),
      ]),
      modulePlan("운영 자동화 확장", [
        lessonPlan("배치 작업으로 묶기", "여러 수업의 더빙과 자막 생성을 한 번에 예약하는 구조를 생각합니다.", 22),
        lessonPlan("실패한 작업 재시도", "API 오류, 네트워크 실패, 저장 실패를 안전하게 재시도합니다.", 20),
        lessonPlan("로그와 비용 추적", "어떤 수업에 얼마의 비용이 들었는지 운영자가 볼 수 있게 합니다.", 19),
        lessonPlan("정식 인코딩 서버로 옮기는 시점", "로컬 운영에서 서버/큐 기반 운영으로 넘어갈 기준을 세웁니다.", 20),
      ]),
    ]),
  },
  {
    id: 107,
    title: "1인 강사의 정산과 운영 장부",
    slug: "solo-instructor-ledger",
    shortDescription: "수강신청, 입금 확인, 정산 기준, 수동 승인까지 설계합니다.",
    description: "초기 마켓플레이스 운영에 필요한 장부 흐름을 만듭니다.",
    category: "비즈니스",
    level: "입문",
    languageCode: "ko",
    tags: ["정산", "입금확인", "운영"],
    seoKeywords: ["강의 정산", "수동 입금 확인", "마켓플레이스 운영"],
    targetAudience: "초기 수동 정산으로 강의 플랫폼을 운영하려는 창업자",
    requirements: "기본적인 매출/정산 개념",
    learningOutcomes: ["정산 기준 기록", "수동 입금 승인", "정산 큐 설계"],
    metaTitle: "1인 강사의 정산과 운영 장부 | 링구스트",
    metaDescription: "초기 강의 플랫폼의 입금 확인, 운영 정산, 수동 승인 흐름을 다루는 강의입니다.",
    ogImageUrl: previewImages[6],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-01T00:00:00.000Z",
    enrollmentEndAt: "2026-05-30T14:59:59.000Z",
    enrollmentCapacity: 50,
    enrollmentAppliedCount: 11,
    price: 49000,
    discountPrice: 35000,
    imageUrl: previewImages[6],
    createdAt: "2026-05-07T00:00:00.000Z",
    purchaseCount: 156,
    reviewCount: 21,
    avgRating: 4.67,
    likeCount: 77,
    instructor: { id: 9007, nickname: "운영노트", email: "ops@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-06T00:00:00.000Z",
    includedFeatures: ["정산 장부 템플릿", "입금 확인 운영표", "초기 수수료 정책 예시", "운영자 체크리스트"],
    relatedTopics: ["Instructor operations", "Bank transfer", "Payouts", "Ledger", "Manual approval"],
    sections: buildMockSections(107, [
      modulePlan("초기 장부 구조", [
        lessonPlan("마켓플레이스 장부가 필요한 이유", "수강 신청, 입금 확인, 승인, 정산을 같은 흐름에서 봐야 하는 이유를 정리합니다.", 14, ["ledger-template.xlsx"]),
        lessonPlan("강의별 매출 항목", "정가, 할인 금액, 실제 입금액, 수수료율, 정산 예정액을 나눕니다.", 16),
        lessonPlan("판매자별 정산 그룹", "여러 강의 판매자의 매출을 판매자 단위로 묶어 봅니다.", 15),
        lessonPlan("초기에는 엑셀로도 버티는 기준", "자동화보다 중요한 기록 항목과 수동 확인 절차를 정합니다.", 14),
      ]),
      modulePlan("계좌입금 확인 흐름", [
        lessonPlan("수강 신청 상태 설계", "신청, 입금 대기, 확인 완료, 반려, 승인 상태를 나눕니다.", 15),
        lessonPlan("입금자명과 신청자 매칭", "입금자명이 다를 때 운영자가 확인해야 할 정보를 정리합니다.", 16),
        lessonPlan("판매자 확인과 최고관리자 확인", "수수료가 0%일 때와 1% 이상일 때 승인 주체가 달라지는 흐름을 설계합니다.", 18),
        lessonPlan("중복 신청과 부분 입금", "운영자가 실제로 자주 만나는 예외 케이스를 처리합니다.", 14),
      ]),
      modulePlan("수수료 정책", [
        lessonPlan("0% 이벤트 정책 설계", "초기에는 무료로 보이되 나중에 수수료를 켤 수 있게 데이터를 남깁니다.", 15),
        lessonPlan("1% 이상 수수료가 켜지는 순간", "판매자가 플랫폼에 입금한 뒤 최종 수강 승인되는 흐름을 정리합니다.", 17),
        lessonPlan("수수료 계산과 반올림", "원 단위 정산에서 생기는 반올림과 할인 적용 순서를 정합니다.", 14),
        lessonPlan("판매자에게 안내할 문구", "수수료, 입금 방식, 승인 지연 가능성을 명확하게 안내합니다.", 13),
      ]),
      modulePlan("정산 대기열 만들기", [
        lessonPlan("정산 대상 필터링", "승인된 수강권만 정산 대상에 들어가도록 조건을 정합니다.", 15),
        lessonPlan("판매자별 정산 카드", "판매자, 강의, 신청 수, 정산 예정액을 한눈에 보이게 만듭니다.", 16),
        lessonPlan("수동 지급 완료 처리", "운영자가 실제 송금한 뒤 지급 완료 상태를 남깁니다.", 14),
        lessonPlan("정산 보류와 메모", "분쟁, 환불, 오입금이 있을 때 정산을 잠시 멈추는 방법을 둡니다.", 15),
      ]),
      modulePlan("운영 리스크와 확장", [
        lessonPlan("환불과 취소 기록", "수동 입금 운영에서 가장 위험한 환불/취소 기록을 어떻게 남길지 정합니다.", 16),
        lessonPlan("월말 정산 리허설", "한 달 운영 후 판매자별 정산표를 만드는 순서를 연습합니다.", 15),
        lessonPlan("결제 시스템 도입 전환", "나중에 토스페이먼츠를 붙여도 기존 신청/정산 데이터가 이어지게 합니다.", 17),
        lessonPlan("운영자가 봐야 할 지표", "미입금, 승인 대기, 정산 대기, 지급 완료 지표를 대시보드로 묶습니다.", 15),
      ]),
    ]),
  },
  {
    id: 108,
    title: "초보 판매자용 첫 강의 출시",
    slug: "first-course-launch",
    shortDescription: "한 편의 공개 영상에서 첫 유료 커리큘럼까지 필요한 최소 단계를 정리합니다.",
    description: "강의를 처음 파는 사람에게 필요한 등록과 출시 체크리스트입니다.",
    category: "크리에이터",
    level: "입문",
    languageCode: "ko",
    tags: ["출시", "공개영상", "판매"],
    seoKeywords: ["첫 강의 출시", "강의 판매", "공개 강의"],
    targetAudience: "첫 유료 강의를 출시하려는 초보 판매자",
    requirements: "판매할 주제와 1개 이상의 공개 영상",
    learningOutcomes: ["출시 체크리스트", "공개 영상 구성", "판매 페이지 기본 필드"],
    metaTitle: "초보 판매자용 첫 강의 출시 | 링구스트",
    metaDescription: "첫 강의 출시를 위한 등록, 공개 영상, 판매 페이지 체크리스트 강의입니다.",
    ogImageUrl: previewImages[7],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-06-01T00:00:00.000Z",
    enrollmentEndAt: "2026-06-21T14:59:59.000Z",
    enrollmentCapacity: 45,
    enrollmentAppliedCount: 0,
    price: 69000,
    discountPrice: 49000,
    imageUrl: previewImages[7],
    createdAt: "2026-05-08T00:00:00.000Z",
    purchaseCount: 221,
    reviewCount: 28,
    avgRating: 4.7,
    likeCount: 93,
    instructor: { id: 9008, nickname: "첫강의클럽", email: "launch@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-13T00:00:00.000Z",
    includedFeatures: ["첫 출시 체크리스트", "소개 수업 스크립트", "상세 페이지 필드 예시", "모집 안내 메시지"],
    relatedTopics: ["Course launch", "Creator onboarding", "Preview lesson", "Sales page", "Cohort launch"],
    sections: buildMockSections(108, [
      modulePlan("첫 강의 상품 정의", [
        lessonPlan("처음 팔 결과물 하나 정하기", "처음부터 모든 지식을 담지 않고 수강생이 얻을 결과 하나로 좁힙니다.", 17, ["first-offer-canvas.pdf"]),
        lessonPlan("대상 수강생을 좁히는 법", "초보자, 실무자, 창업자 중 누구에게 맞는 강의인지 명확히 정합니다.", 16),
        lessonPlan("가격대와 분량 감각 잡기", "정가와 할인 가격을 정할 때 커리큘럼 분량과 결과물을 함께 계산합니다.", 18),
        lessonPlan("무료 콘텐츠와 유료 강의의 경계", "홍보용 공개 콘텐츠와 유료 수업에서 제공할 깊이를 구분합니다.", 17),
      ]),
      modulePlan("등록 전 준비물", [
        lessonPlan("강의 개요 문서 만들기", "제목, 한 줄 소개, 상세 설명, 추천 대상, 준비물을 하나의 문서로 정리합니다.", 16),
        lessonPlan("섹션과 수업 초안 작성", "섹션 아래 수업이 자연스럽게 묶이도록 첫 커리큘럼을 만듭니다.", 18),
        lessonPlan("촬영 전 체크리스트", "마이크, 화면, 예제 파일, 대본, 조명 등 최소 준비 항목을 점검합니다.", 16),
        lessonPlan("자료 파일 정리", "수강생이 받을 워크시트, 템플릿, 예제 파일을 수업별로 묶습니다.", 15),
      ]),
      modulePlan("판매 페이지 만들기", [
        lessonPlan("첫 화면 카피 작성", "수강생이 5초 안에 강의의 결과와 대상을 이해하도록 구성합니다.", 17),
        lessonPlan("배우게 되는 것 작성", "추상적인 장점이 아니라 수강 후 할 수 있는 행동으로 씁니다.", 16),
        lessonPlan("프리뷰 이미지 선정", "강의 주제와 가격대가 느껴지는 대표 이미지를 선택합니다.", 15),
        lessonPlan("FAQ와 환불 안내", "구매 전에 자주 묻는 질문과 운영 정책을 미리 작성합니다.", 15),
      ]),
      modulePlan("시즌 모집 설정", [
        lessonPlan("모집 기간과 정원 정하기", "처음 시즌의 신청 기간, 마감일, 정원을 무리 없는 수준으로 정합니다.", 17),
        lessonPlan("계좌입금 안내 작성", "수강생에게 보일 입금 계좌, 입금자명, 확인 시간을 명확히 안내합니다.", 16),
        lessonPlan("모집 완료 상태 만들기", "정원이 찼거나 기간이 끝났을 때 다음 시즌 안내를 보여줍니다.", 16),
        lessonPlan("신청자 리스트 확인", "판매자가 신청자와 입금 상태를 관리하는 화면을 이해합니다.", 17),
      ]),
      modulePlan("첫 수업 촬영과 편집", [
        lessonPlan("소개 수업의 역할", "강사의 스타일과 강의 난이도를 보여주는 첫 수업을 설계합니다.", 17),
        lessonPlan("실습 수업 녹화 기준", "실습 화면에서 글자 크기, 속도, 설명 순서를 맞춥니다.", 18),
        lessonPlan("수업별 길이 조절", "너무 긴 수업을 나누고 짧은 수업은 묶는 기준을 잡습니다.", 16),
        lessonPlan("업로드 전 파일 정리", "원본 영상, 썸네일, 자료 파일을 나중에 찾기 쉽게 정리합니다.", 15),
      ]),
      modulePlan("출시 후 운영", [
        lessonPlan("신청자에게 보내는 첫 메시지", "입금 안내, 승인 예상 시간, 수강 시작 방법을 담은 메시지를 만듭니다.", 16),
        lessonPlan("초기 피드백 받기", "첫 수강생에게 어떤 질문을 던져 다음 시즌을 개선할지 정합니다.", 15),
        lessonPlan("리뷰 요청 타이밍", "완강 직후 자연스럽게 리뷰를 요청하는 흐름을 만듭니다.", 14),
        lessonPlan("다음 시즌 개선 계획", "가격, 커리큘럼, 상세 페이지, 모집 문구를 어디부터 바꿀지 정합니다.", 16),
      ]),
    ]),
  },
  {
    id: 201,
    title: "Unreal Engine 5 게임 개발 입문",
    slug: "unreal-engine-5-game-development",
    shortDescription: "블루프린트와 C++로 액션 RPG 프로토타입을 만들며 게임 개발의 전체 흐름을 익힙니다.",
    description:
      "게임 개발 입문자가 Unreal Engine 5 환경에서 프로젝트 구조, 블루프린트, C++ Gameplay Framework, 캐릭터 조작, 레벨 디자인, Niagara VFX, 패키징까지 한 번에 경험하는 실전형 강의입니다. 강의가 끝나면 포트폴리오로 보여줄 수 있는 짧은 액션 RPG 프로토타입을 완성합니다.",
    category: "게임 개발",
    level: "입문-중급",
    languageCode: "ko",
    tags: ["Unreal Engine 5", "UE5", "게임 개발", "Blueprint", "C++"],
    seoKeywords: [
      "언리얼 엔진 강의",
      "Unreal Engine 5 강의",
      "UE5 게임 개발",
      "게임 개발 입문",
      "블루프린트 강의",
      "언리얼 C++",
      "액션 RPG 만들기",
    ],
    targetAudience: "게임 개발 입문자, Unity 이후 Unreal Engine으로 넘어오려는 개발자, 포트폴리오용 게임 프로토타입을 만들고 싶은 수강생",
    requirements: "기본적인 컴퓨터 사용 능력, C++ 기초 문법을 알면 좋지만 필수는 아닙니다. Unreal Engine 5 설치가 필요합니다.",
    learningOutcomes: [
      "Unreal Engine 5 프로젝트 구조와 에디터 흐름 이해",
      "블루프린트와 C++를 함께 쓰는 Gameplay Framework 설계",
      "캐릭터 이동, 카메라, 전투 입력, UI, 세이브 데이터 구현",
      "Niagara VFX와 라이팅을 활용한 짧은 액션 RPG 포트폴리오 제작",
    ],
    metaTitle: "Unreal Engine 5 게임 개발 입문 | 링구스트",
    metaDescription:
      "Unreal Engine 5, 블루프린트, C++ Gameplay Framework로 액션 RPG 프로토타입을 만드는 게임 개발 입문 강의입니다.",
    ogImageUrl: previewImages[8],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-20T00:00:00.000Z",
    enrollmentEndAt: "2026-06-24T14:59:59.000Z",
    enrollmentCapacity: 36,
    enrollmentAppliedCount: 18,
    price: 129000,
    discountPrice: 99000,
    imageUrl: previewImages[8],
    createdAt: "2026-05-14T00:00:00.000Z",
    purchaseCount: 638,
    reviewCount: 84,
    avgRating: 4.82,
    likeCount: 231,
    instructor: { id: 9201, nickname: "게임빌더", email: "gamedev@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-15T00:00:00.000Z",
    includedFeatures: ["UE5 프로젝트 템플릿", "블루프린트 실습 노트", "C++ Gameplay 예제", "포트폴리오 패키징 체크리스트"],
    relatedTopics: ["Unreal Engine 5", "Game development", "Blueprint", "C++", "Action RPG", "Niagara VFX"],
    sections: buildMockSections(201, [
      modulePlan("게임 개발 로드맵과 UE5 프로젝트 준비", [
        lessonPlan("게임 개발 입문자가 먼저 알아야 할 전체 흐름", "기획, 프로토타입, 구현, 테스트, 패키징이 어떤 순서로 이어지는지 Unreal Engine 기준으로 봅니다.", 17, ["ue5-roadmap.pdf"]),
        lessonPlan("Unreal Engine 5 설치와 프로젝트 생성", "엔진 버전 선택, 템플릿, Starter Content, 프로젝트 폴더 구조를 안정적으로 준비합니다.", 18),
        lessonPlan("에디터 인터페이스와 기본 조작", "Viewport, World Outliner, Details, Content Browser를 실습 기준으로 익힙니다.", 20),
        lessonPlan("샘플 액션 RPG 목표 정의", "이번 강의에서 만들 전투, 이동, UI, VFX 범위를 포트폴리오 관점으로 정리합니다.", 16),
      ]),
      modulePlan("블루프린트 기초와 프로토타입", [
        lessonPlan("블루프린트가 게임 로직을 표현하는 방식", "노드, 이벤트, 변수, 함수, 매크로의 역할을 게임 흐름에 맞게 이해합니다.", 18),
        lessonPlan("Actor와 Component로 상호작용 만들기", "문, 발판, 회복 아이템처럼 월드에 배치되는 오브젝트를 구성합니다.", 20),
        lessonPlan("충돌과 트리거 이벤트", "Overlap, Hit, Collision Channel을 사용해 플레이어와 월드의 상호작용을 만듭니다.", 20),
        lessonPlan("프로토타입 속도를 높이는 블루프린트 규칙", "나중에 C++로 옮길 수 있게 블루프린트 그래프를 정리하는 습관을 만듭니다.", 19, ["blueprint-style-guide.md"]),
      ]),
      modulePlan("C++ Gameplay Framework", [
        lessonPlan("Unreal C++ 프로젝트 구조 읽기", "Module, Build.cs, Header, Source, UCLASS 매크로가 어떤 역할을 하는지 봅니다.", 22),
        lessonPlan("GameMode, Pawn, Character, PlayerController", "플레이어 캐릭터와 게임 규칙이 어떤 클래스에 나뉘어 들어가는지 설계합니다.", 24),
        lessonPlan("UPROPERTY와 UFUNCTION 기초", "에디터 노출, 블루프린트 호출, 메모리 관리에 필요한 매크로를 실습합니다.", 22),
        lessonPlan("블루프린트와 C++ 책임 나누기", "빠른 튜닝은 블루프린트, 핵심 규칙은 C++로 두는 기준을 정합니다.", 21),
      ]),
      modulePlan("캐릭터 이동, 입력, 카메라", [
        lessonPlan("Enhanced Input으로 이동 입력 만들기", "키보드와 게임패드 입력 액션을 분리하고 매핑 컨텍스트를 설정합니다.", 20),
        lessonPlan("캐릭터 이동과 회전 감각 조정", "이동 속도, 회전, 가속, 점프를 조정해 조작감을 다듬습니다.", 23),
        lessonPlan("스프링암과 3인칭 카메라", "카메라 거리, 충돌, 시야각을 조정해 액션 게임의 기본 시점을 만듭니다.", 21),
        lessonPlan("공격 입력과 간단한 콤보", "입력 버퍼와 상태 값을 사용해 기본 공격과 후속 공격 흐름을 만듭니다.", 22),
      ]),
      modulePlan("레벨 디자인과 라이팅", [
        lessonPlan("플레이 가능한 회색 박스 맵 만들기", "완성된 배경보다 먼저 이동, 전투, 시야가 검증되는 테스트 맵을 만듭니다.", 21),
        lessonPlan("Static Mesh와 Material 배치", "기본 메시와 머티리얼을 사용해 공간의 테마와 동선을 만듭니다.", 22),
        lessonPlan("Lumen 라이팅 기초", "전역 조명, 반사, 노출 값을 조정해 UE5다운 장면 밀도를 만듭니다.", 20),
        lessonPlan("게임플레이를 돕는 공간 연출", "적 배치, 보상 위치, 안전 지대, 시야 유도를 레벨 디자인에 반영합니다.", 23),
      ]),
      modulePlan("UI, 인벤토리, 세이브", [
        lessonPlan("UMG로 체력과 스태미나 UI 만들기", "Widget Blueprint와 바인딩을 사용해 플레이어 상태를 화면에 표시합니다.", 20),
        lessonPlan("아이템 획득과 간단한 인벤토리", "Data Asset과 구조체를 사용해 아이템 정보를 관리합니다.", 22),
        lessonPlan("일시정지와 설정 메뉴", "게임 흐름을 멈추고 입력 모드를 UI로 전환하는 과정을 구현합니다.", 21),
        lessonPlan("SaveGame으로 진행 상태 저장", "플레이어 위치, 획득 아이템, 설정 값을 저장하고 불러옵니다.", 18, ["savegame-checklist.pdf"]),
      ]),
      modulePlan("Niagara VFX와 오디오 연출", [
        lessonPlan("Niagara 시스템 구조", "Emitter, System, Parameter의 관계를 이해하고 기본 파티클을 만듭니다.", 19),
        lessonPlan("공격 이펙트와 피격 피드백", "타격 순간에 VFX, 카메라 흔들림, 사운드가 함께 반응하도록 구성합니다.", 20),
        lessonPlan("마법 포털과 환경 이펙트", "UE5 장면에서 눈에 띄는 포털, 안개, 빛 입자를 구성합니다.", 21),
        lessonPlan("사운드 큐와 믹싱 기본", "발소리, 공격음, 배경음을 구분해 플레이 감각을 높입니다.", 20),
      ]),
      modulePlan("포트폴리오 패키징과 출시 준비", [
        lessonPlan("빌드 전 프로젝트 정리", "사용하지 않는 에셋, 입력 설정, 맵 기본값을 정리합니다.", 22),
        lessonPlan("Windows 패키징과 오류 해결", "패키징 실패 로그를 읽고 SDK, 플러그인, 경로 문제를 해결합니다.", 24),
        lessonPlan("플레이 테스트 체크리스트", "프레임, 충돌, UI, 저장, 입력을 출시 전 기준으로 점검합니다.", 20, ["playtest-checklist.xlsx"]),
        lessonPlan("포트폴리오 영상과 설명 작성", "완성한 프로토타입을 짧은 영상과 설명으로 정리해 보여주는 방법을 배웁니다.", 24),
      ]),
    ]),
  },
  {
    id: 202,
    title: "Unity 6 모바일 액션 게임 입문",
    slug: "unity-6-mobile-action-game",
    shortDescription: "Unity와 C#으로 모바일 액션 게임의 조작, 전투, UI, 빌드 과정을 완성합니다.",
    description:
      "Unity 6와 C#을 사용해 모바일 액션 게임 프로토타입을 처음부터 완성합니다. 터치 입력, 캐릭터 이동, 적 AI, 전투, UI, 광고/인앱 결제 확장 지점, Android 빌드까지 게임 개발 입문자가 실제 출시 흐름을 이해할 수 있게 구성했습니다.",
    category: "게임 개발",
    level: "입문",
    languageCode: "ko",
    tags: ["Unity", "C#", "모바일 게임", "게임 개발"],
    seoKeywords: ["Unity 강의", "유니티 게임 개발", "C# 게임 개발", "모바일 게임 만들기", "게임 개발 입문", "Unity 6"],
    targetAudience: "처음 모바일 게임을 만들어보는 입문자, Unity로 포트폴리오를 준비하는 학생, C# 기반 게임 개발을 시작하려는 수강생",
    requirements: "기초 프로그래밍 경험이 있으면 좋습니다. Unity Hub와 Unity 6 설치가 필요합니다.",
    learningOutcomes: ["Unity 프로젝트 구조 이해", "C# 스크립트로 캐릭터와 전투 구현", "모바일 터치 입력과 UI 구성", "Android 테스트 빌드 생성"],
    metaTitle: "Unity 6 모바일 액션 게임 입문 | 링구스트",
    metaDescription: "Unity 6와 C#으로 모바일 액션 게임 프로토타입을 만드는 게임 개발 입문 강의입니다.",
    ogImageUrl: previewImages[9],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-15T00:00:00.000Z",
    enrollmentEndAt: "2026-06-20T14:59:59.000Z",
    enrollmentCapacity: 42,
    enrollmentAppliedCount: 25,
    price: 99000,
    discountPrice: 79000,
    imageUrl: previewImages[9],
    createdAt: "2026-05-15T00:00:00.000Z",
    purchaseCount: 912,
    reviewCount: 126,
    avgRating: 4.76,
    likeCount: 284,
    instructor: { id: 9202, nickname: "유니티메이커", email: "unity@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-15T00:00:00.000Z",
    includedFeatures: ["Unity 프로젝트 템플릿", "C# 전투 스크립트", "모바일 UI 프리셋", "Android 빌드 체크리스트"],
    relatedTopics: ["Unity", "C#", "Mobile game", "Touch input", "Action game"],
    sections: buildMockSections(202, [
      modulePlan("Unity 모바일 게임 개발 준비", [
        lessonPlan("Unity 6 프로젝트와 폴더 구조", "Assets, Scenes, Scripts, Prefabs를 실제 모바일 게임 기준으로 정리합니다.", 20, ["unity-project-setup.pdf"]),
        lessonPlan("2D와 3D 중 무엇을 선택할까", "처음 만드는 모바일 액션 게임에서 2D, 2.5D, 3D 선택 기준을 봅니다.", 18),
        lessonPlan("씬, 게임 오브젝트, 컴포넌트", "Unity의 핵심 구성 단위를 작은 실습으로 이해합니다.", 21),
        lessonPlan("모바일 해상도와 카메라 기본값", "여러 기기에서 깨지지 않는 화면 비율과 카메라 구성을 잡습니다.", 19),
      ]),
      modulePlan("C# 스크립트와 캐릭터 조작", [
        lessonPlan("MonoBehaviour 생명주기", "Awake, Start, Update, FixedUpdate가 게임 루프에서 언제 호출되는지 익힙니다.", 22),
        lessonPlan("캐릭터 이동과 회전", "Rigidbody와 Transform 이동의 차이를 보고 모바일 액션에 맞는 방식을 고릅니다.", 24),
        lessonPlan("터치 입력과 가상 조이스틱", "모바일 화면에서 자연스러운 이동 입력을 구현합니다.", 23),
        lessonPlan("애니메이션 파라미터 연결", "Animator Controller와 C# 값을 연결해 움직임과 공격 애니메이션을 제어합니다.", 22),
      ]),
      modulePlan("전투와 적 AI", [
        lessonPlan("공격 판정 만들기", "범위 공격, 충돌 판정, 쿨다운을 사용해 기본 전투를 만듭니다.", 23),
        lessonPlan("체력과 데미지 시스템", "플레이어와 적이 공통으로 사용하는 데미지 인터페이스를 설계합니다.", 22),
        lessonPlan("간단한 추적 AI", "NavMesh 또는 거리 기반 추적으로 적이 플레이어를 따라오게 만듭니다.", 24),
        lessonPlan("스폰과 웨이브 구조", "스테이지마다 적이 등장하고 난이도가 올라가는 흐름을 만듭니다.", 21, ["wave-design-sheet.xlsx"]),
      ]),
      modulePlan("UI, 사운드, 피드백", [
        lessonPlan("체력바와 스킬 버튼", "Canvas, Anchor, Safe Area를 고려해 모바일 UI를 구성합니다.", 21),
        lessonPlan("피격 피드백과 카메라 흔들림", "짧은 화면 효과와 진동으로 타격감을 살립니다.", 19),
        lessonPlan("사운드 매니저 만들기", "효과음과 배경음을 분리하고 반복 재생과 볼륨 설정을 구현합니다.", 20),
        lessonPlan("게임 오버와 재시작 플로우", "패배, 재도전, 홈으로 돌아가기 흐름을 UI로 연결합니다.", 18),
      ]),
      modulePlan("모바일 빌드와 출시 준비", [
        lessonPlan("Android 빌드 설정", "패키지명, 아이콘, orientation, scripting backend를 설정합니다.", 23),
        lessonPlan("기기 테스트와 성능 체크", "프레임 드랍, 발열, 메모리 사용을 실제 기기에서 확인합니다.", 22),
        lessonPlan("광고와 인앱 결제 확장 지점", "MVP 단계에서 코드를 망치지 않고 수익화 지점을 남기는 방법을 봅니다.", 21),
        lessonPlan("포트폴리오 제출용 빌드 만들기", "APK/AAB, 플레이 영상, README를 함께 준비합니다.", 20, ["mobile-release-checklist.pdf"]),
      ]),
      modulePlan("실전 미니 프로젝트 폴리싱", [
        lessonPlan("게임 밸런스 빠르게 조정하기", "적 체력, 공격력, 보상 주기를 테스트하면서 재미의 기준을 잡습니다.", 20),
        lessonPlan("스테이지 클리어 연출", "클리어 컷신, 보상 UI, 다음 스테이지 이동을 연결합니다.", 20),
        lessonPlan("초보자가 자주 만드는 버그 수정", "입력 중복, 오브젝트 누락, 씬 전환 오류를 실제 사례로 해결합니다.", 21),
        lessonPlan("최종 플레이 영상 촬영", "완성된 모바일 액션 게임을 포트폴리오 영상으로 정리합니다.", 19),
      ]),
    ]),
  },
  {
    id: 203,
    title: "Godot 4 픽셀 RPG 만들기",
    slug: "godot-4-pixel-rpg",
    shortDescription: "Godot 4와 GDScript로 타일맵, 대화, 전투가 있는 2D 픽셀 RPG를 만듭니다.",
    description:
      "가볍고 빠른 오픈소스 엔진 Godot 4로 2D 픽셀 RPG를 제작합니다. 타일맵, 플레이어 이동, NPC 대화, 턴제 전투, 인벤토리, 세이브까지 독립 게임 개발자가 자주 쓰는 구조를 작은 프로젝트로 완성합니다.",
    category: "게임 개발",
    level: "입문",
    languageCode: "ko",
    tags: ["Godot", "GDScript", "Pixel RPG", "2D 게임"],
    seoKeywords: ["Godot 강의", "고도 엔진 강의", "GDScript", "픽셀 RPG 만들기", "2D 게임 개발", "인디 게임 개발"],
    targetAudience: "부담 없이 게임 개발을 시작하고 싶은 입문자, 픽셀 RPG를 만들고 싶은 인디 개발자, Godot을 처음 배우는 수강생",
    requirements: "프로그래밍 기초가 있으면 좋지만, GDScript 문법은 강의 안에서 같이 다룹니다.",
    learningOutcomes: ["Godot 4 노드와 씬 구조 이해", "타일맵 기반 2D 월드 구성", "NPC 대화와 전투 시스템 구현", "세이브 파일과 간단한 퀘스트 흐름 제작"],
    metaTitle: "Godot 4 픽셀 RPG 만들기 | 링구스트",
    metaDescription: "Godot 4와 GDScript로 타일맵, 대화, 전투, 인벤토리가 있는 2D 픽셀 RPG를 만드는 강의입니다.",
    ogImageUrl: previewImages[10],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-15T00:00:00.000Z",
    enrollmentEndAt: "2026-06-18T14:59:59.000Z",
    enrollmentCapacity: 48,
    enrollmentAppliedCount: 31,
    price: 69000,
    discountPrice: 49000,
    imageUrl: previewImages[10],
    createdAt: "2026-05-15T00:00:00.000Z",
    purchaseCount: 744,
    reviewCount: 98,
    avgRating: 4.71,
    likeCount: 241,
    instructor: { id: 9203, nickname: "인디도트", email: "godot@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-15T00:00:00.000Z",
    includedFeatures: ["Godot 4 샘플 프로젝트", "픽셀 타일셋 가이드", "대화 데이터 예제", "RPG 세이브 구조"],
    relatedTopics: ["Godot", "GDScript", "Pixel art", "2D RPG", "Indie game"],
    sections: buildMockSections(203, [
      modulePlan("Godot 4 기초와 프로젝트 구조", [
        lessonPlan("Godot을 게임 입문에 쓰기 좋은 이유", "엔진의 가벼움, 노드 구조, 2D 워크플로우를 다른 엔진과 비교합니다.", 16, ["godot-rpg-roadmap.pdf"]),
        lessonPlan("씬과 노드 구조 이해", "Player, Map, UI, Manager를 씬으로 나누는 기준을 익힙니다.", 19),
        lessonPlan("GDScript 핵심 문법", "변수, 함수, 시그널, 타입 힌트를 게임 예제로 익힙니다.", 22),
        lessonPlan("프로젝트 폴더와 리소스 규칙", "씬, 스크립트, 타일셋, 사운드 파일을 나중에 커지지 않게 정리합니다.", 18),
      ]),
      modulePlan("타일맵과 플레이어 이동", [
        lessonPlan("TileMap으로 마을 만들기", "픽셀 타일셋을 가져오고 충돌 레이어가 있는 마을 맵을 만듭니다.", 22),
        lessonPlan("플레이어 4방향 이동", "CharacterBody2D와 입력 맵으로 고전 RPG 이동을 구현합니다.", 21),
        lessonPlan("카메라와 맵 경계", "Camera2D가 플레이어를 따라오되 맵 밖을 보지 않게 조정합니다.", 18),
        lessonPlan("상호작용 가능한 오브젝트", "상자, 문, 표지판을 같은 인터페이스로 처리합니다.", 20),
      ]),
      modulePlan("NPC 대화와 퀘스트", [
        lessonPlan("대화 데이터 구조 만들기", "JSON 또는 Resource로 대화 문장을 관리하는 방식을 봅니다.", 22),
        lessonPlan("대화 UI와 타이핑 효과", "말풍선, 이름표, 다음 버튼, 텍스트 등장 효과를 만듭니다.", 21),
        lessonPlan("퀘스트 상태 관리", "수락 전, 진행 중, 완료 상태를 플레이어 데이터에 저장합니다.", 20),
        lessonPlan("NPC 조건 분기", "퀘스트 상태에 따라 다른 대사를 보여주는 흐름을 만듭니다.", 19, ["dialogue-state-table.xlsx"]),
      ]),
      modulePlan("턴제 전투 시스템", [
        lessonPlan("전투 씬 전환", "월드에서 적과 마주쳤을 때 전투 씬으로 넘어가는 구조를 만듭니다.", 20),
        lessonPlan("플레이어와 몬스터 스탯", "HP, 공격력, 방어력, 속도를 데이터로 분리합니다.", 21),
        lessonPlan("턴 순서와 명령 선택", "공격, 방어, 아이템 사용 같은 기본 명령을 구현합니다.", 23),
        lessonPlan("전투 결과와 경험치", "승리, 패배, 보상, 레벨업 흐름을 정리합니다.", 20),
      ]),
      modulePlan("인벤토리와 저장", [
        lessonPlan("아이템 데이터베이스", "포션, 장비, 퀘스트 아이템을 Resource로 관리합니다.", 20),
        lessonPlan("인벤토리 UI 구성", "아이템 목록, 선택 상태, 설명 패널을 만듭니다.", 21),
        lessonPlan("Save/Load 구현", "플레이어 위치, 퀘스트, 인벤토리를 파일로 저장하고 불러옵니다.", 22),
        lessonPlan("웹/데스크톱 내보내기", "Godot Export Preset을 사용해 테스트 빌드를 만듭니다.", 19, ["godot-export-checklist.pdf"]),
      ]),
      modulePlan("인디 RPG 완성도 높이기", [
        lessonPlan("타이틀 화면과 메뉴 흐름", "시작, 이어하기, 설정 메뉴를 작은 게임답게 구성합니다.", 20),
        lessonPlan("마을 NPC와 전투 보상 연결", "퀘스트 완료와 전투 보상이 월드 상태에 반영되도록 만듭니다.", 21),
        lessonPlan("사운드와 화면 전환 폴리싱", "픽셀 RPG에 어울리는 효과음, 페이드, 전환 연출을 붙입니다.", 20),
        lessonPlan("인디 게임 소개 페이지 만들기", "스크린샷, 조작법, 다운로드 링크를 정리해 공개 가능한 형태로 마무리합니다.", 19),
      ]),
    ]),
  },
  {
    id: 204,
    title: "Blender에서 Unreal까지 게임 환경 아트",
    slug: "blender-to-unreal-environment-art",
    shortDescription: "Blender 모델링과 Unreal Engine 라이팅으로 포트폴리오용 게임 환경을 완성합니다.",
    description:
      "게임 환경 아티스트 입문자를 위한 실전 강의입니다. Blender에서 모듈러 에셋을 만들고, Unreal Engine으로 가져와 머티리얼, 라이팅, 포스트 프로세스, 카메라 연출을 적용해 AAA 느낌의 환경 아트 포트폴리오 장면을 완성합니다.",
    category: "게임 개발",
    level: "입문-중급",
    languageCode: "ko",
    tags: ["Blender", "Unreal Engine", "환경 아트", "레벨 디자인"],
    seoKeywords: ["게임 환경 아트", "Blender 강의", "언리얼 환경 아트", "Unreal Engine 라이팅", "게임 그래픽 포트폴리오"],
    targetAudience: "게임 배경 아트를 시작하려는 아티스트, Blender에서 Unreal Engine으로 넘어가고 싶은 수강생, 포트폴리오 장면을 만들고 싶은 사람",
    requirements: "Blender 기본 조작 경험이 있으면 좋습니다. Unreal Engine 5 설치가 필요합니다.",
    learningOutcomes: ["모듈러 환경 에셋 제작", "Blender에서 Unreal로 에셋 가져오기", "머티리얼과 라이팅으로 장면 완성", "게임 환경 아트 포트폴리오 샷 제작"],
    metaTitle: "Blender에서 Unreal까지 게임 환경 아트 | 링구스트",
    metaDescription: "Blender 모델링과 Unreal Engine 라이팅으로 포트폴리오용 게임 환경 아트를 완성하는 강의입니다.",
    ogImageUrl: previewImages[11],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-15T00:00:00.000Z",
    enrollmentEndAt: "2026-06-22T14:59:59.000Z",
    enrollmentCapacity: 30,
    enrollmentAppliedCount: 17,
    price: 109000,
    discountPrice: 84000,
    imageUrl: previewImages[11],
    createdAt: "2026-05-15T00:00:00.000Z",
    purchaseCount: 506,
    reviewCount: 64,
    avgRating: 4.84,
    likeCount: 192,
    instructor: { id: 9204, nickname: "월드아티스트", email: "environment@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-15T00:00:00.000Z",
    includedFeatures: ["모듈러 에셋 제작표", "Unreal 임포트 프리셋", "라이팅 체크리스트", "포트폴리오 샷 가이드"],
    relatedTopics: ["Blender", "Unreal Engine", "Environment art", "Lighting", "Portfolio"],
    sections: buildMockSections(204, [
      modulePlan("환경 아트 포트폴리오 설계", [
        lessonPlan("좋은 게임 환경 샷의 구성", "실루엣, 동선, 명암, 스토리텔링을 포트폴리오 기준으로 봅니다.", 18, ["environment-shot-plan.pdf"]),
        lessonPlan("레퍼런스 보드 만들기", "무드, 재질, 색, 구조를 구분해 레퍼런스를 모읍니다.", 17),
        lessonPlan("모듈러 방식 이해", "벽, 기둥, 바닥, 장식 요소를 반복 가능한 에셋으로 나눕니다.", 20),
        lessonPlan("스케일과 그리드 규칙", "Unreal에서 어긋나지 않도록 Blender 단위와 피벗을 맞춥니다.", 19),
      ]),
      modulePlan("Blender 모듈러 에셋 제작", [
        lessonPlan("기본 형태 블로킹", "큰 형태부터 잡아 환경의 비율과 동선을 검증합니다.", 21),
        lessonPlan("벽, 계단, 기둥 세트 만들기", "반복 배치 가능한 기본 구조물을 제작합니다.", 24),
        lessonPlan("디테일 에셋과 데칼 준비", "작은 장식, 파손, 표면 디테일을 분리해 준비합니다.", 23),
        lessonPlan("UV와 텍셀 밀도 기초", "게임 엔진에서 재질이 깨지지 않도록 UV 기준을 세웁니다.", 22),
      ]),
      modulePlan("Unreal Engine 임포트와 배치", [
        lessonPlan("FBX 임포트 설정", "Scale, collision, material slot을 안전하게 가져옵니다.", 20),
        lessonPlan("모듈러 에셋으로 레벨 조립", "그리드 스냅과 피벗을 사용해 빠르게 공간을 만듭니다.", 23),
        lessonPlan("머티리얼 인스턴스 구성", "색, roughness, normal을 파라미터로 조정할 수 있게 합니다.", 21),
        lessonPlan("Nanite와 LOD 판단", "에셋 특성에 따라 Nanite를 쓸지 LOD를 만들지 결정합니다.", 20),
      ]),
      modulePlan("라이팅과 분위기", [
        lessonPlan("Lumen 기반 기본 조명", "Directional Light, Sky Light, Exposure를 세팅합니다.", 22),
        lessonPlan("주목 지점을 만드는 빛", "플레이어나 카메라가 봐야 할 곳에 시선을 유도합니다.", 21),
        lessonPlan("안개와 포스트 프로세스", "Volumetric Fog, Color Grading으로 장면의 깊이를 만듭니다.", 22),
        lessonPlan("스크린샷용 카메라 세팅", "FOV, 초점거리, 구도를 조정해 포트폴리오 샷을 만듭니다.", 20),
      ]),
      modulePlan("최종 정리와 제출", [
        lessonPlan("장면 최적화 체크", "불필요한 에셋, 과도한 머티리얼, 무거운 조명을 정리합니다.", 20),
        lessonPlan("비포/애프터 비교 이미지", "블로킹부터 최종 샷까지 과정을 보여주는 이미지를 준비합니다.", 18),
        lessonPlan("아트스테이션 업로드 구성", "대표 이미지, 과정 이미지, 설명 문장을 정리합니다.", 19),
        lessonPlan("포트폴리오 리뷰 체크리스트", "채용자가 보는 기준으로 장면을 다시 점검합니다.", 20, ["environment-portfolio-checklist.pdf"]),
      ]),
      modulePlan("쇼케이스 씬 폴리싱", [
        lessonPlan("카메라 동선과 시퀀서", "짧은 포트폴리오 영상을 위해 카메라 이동과 컷을 구성합니다.", 20),
        lessonPlan("히어로 에셋 강조하기", "가장 중요한 오브젝트가 한눈에 보이도록 배치와 조명을 다듬습니다.", 21),
        lessonPlan("스크린샷별 색감 보정", "서로 다른 각도의 이미지가 같은 프로젝트처럼 보이도록 톤을 맞춥니다.", 20),
        lessonPlan("제출용 패키지 정리", "원본 파일, 엔진 프로젝트, 렌더 이미지, 설명 문서를 묶습니다.", 19),
      ]),
    ]),
  },
  {
    id: 205,
    title: "Unreal Engine 5 Niagara VFX 마스터",
    slug: "unreal-engine-5-niagara-vfx",
    shortDescription: "Niagara로 마법, 폭발, 포털, 타격 이펙트를 만들며 게임 VFX 흐름을 익힙니다.",
    description:
      "Unreal Engine 5의 Niagara 시스템을 사용해 게임 VFX를 제작합니다. 파티클 기본기부터 마법 포털, 타격 스파크, 폭발, 환경 이펙트, 머티리얼 연동, 성능 최적화까지 실무에서 쓰는 흐름으로 구성했습니다.",
    category: "게임 개발",
    level: "중급",
    languageCode: "ko",
    tags: ["Unreal Engine 5", "Niagara", "VFX", "게임 그래픽"],
    seoKeywords: ["Niagara 강의", "언리얼 VFX", "Unreal Engine 5 이펙트", "게임 이펙트", "파티클 시스템", "게임 그래픽 강의"],
    targetAudience: "Unreal Engine 기본 조작을 알고 있고, 게임 이펙트와 VFX 포트폴리오를 만들고 싶은 수강생",
    requirements: "Unreal Engine 5 기본 조작 경험, 머티리얼 기초를 알고 있으면 좋습니다.",
    learningOutcomes: ["Niagara Emitter와 System 구조 이해", "마법/타격/폭발 이펙트 제작", "머티리얼과 파티클 파라미터 연결", "게임 성능을 고려한 VFX 최적화"],
    metaTitle: "Unreal Engine 5 Niagara VFX 마스터 | 링구스트",
    metaDescription: "Unreal Engine 5 Niagara로 포털, 폭발, 타격 이펙트를 제작하는 게임 VFX 강의입니다.",
    ogImageUrl: previewImages[12],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-15T00:00:00.000Z",
    enrollmentEndAt: "2026-06-26T14:59:59.000Z",
    enrollmentCapacity: 34,
    enrollmentAppliedCount: 21,
    price: 89000,
    discountPrice: 69000,
    imageUrl: previewImages[12],
    createdAt: "2026-05-15T00:00:00.000Z",
    purchaseCount: 682,
    reviewCount: 91,
    avgRating: 4.88,
    likeCount: 255,
    instructor: { id: 9205, nickname: "이펙트랩", email: "vfx@seed.lingoost.local" },
    lastUpdatedAt: "2026-05-15T00:00:00.000Z",
    includedFeatures: ["Niagara 샘플 시스템", "VFX 머티리얼 프리셋", "타격 이펙트 예제", "최적화 체크리스트"],
    relatedTopics: ["Unreal Engine 5", "Niagara", "VFX", "Particle system", "Game effects"],
    sections: buildMockSections(205, [
      modulePlan("Niagara 기본 구조", [
        lessonPlan("Niagara가 Cascade와 다른 점", "UE5에서 Niagara를 사용하는 이유와 작업 흐름을 정리합니다.", 18, ["niagara-map.pdf"]),
        lessonPlan("Emitter, System, Module", "Niagara의 세 가지 핵심 단위를 예제로 구분합니다.", 21),
        lessonPlan("Spawn과 Update 흐름", "파티클이 태어나고 움직이고 사라지는 과정을 모듈로 제어합니다.", 22),
        lessonPlan("속성 창과 디버깅 보기", "파라미터, bounds, preview 설정을 확인하는 습관을 만듭니다.", 19),
      ]),
      modulePlan("기본 파티클 이펙트", [
        lessonPlan("스파크와 먼지 만들기", "속도, 중력, 크기, 색 변화를 사용해 기본 이펙트를 만듭니다.", 21),
        lessonPlan("리본과 궤적 표현", "검기, 총알 궤적, 이동 흔적에 쓰이는 Ribbon Renderer를 다룹니다.", 23),
        lessonPlan("Sprite와 Mesh Renderer", "2D 텍스처 파티클과 3D 메시 파티클의 차이를 봅니다.", 21),
        lessonPlan("랜덤성과 타이밍", "같은 이펙트가 반복되어도 지루하지 않게 변주를 줍니다.", 20),
      ]),
      modulePlan("전투 이펙트 제작", [
        lessonPlan("근접 타격 스파크", "타격 위치, 방향, 지속 시간을 게임 이벤트와 연결합니다.", 21),
        lessonPlan("폭발 이펙트 레이어링", "섬광, 충격파, 연기, 파편을 레이어로 쌓습니다.", 24),
        lessonPlan("마법 투사체 만들기", "이동하는 projectile과 꼬리 이펙트를 함께 구성합니다.", 22),
        lessonPlan("피격 피드백과 사운드 큐", "VFX가 사운드, 카메라 흔들림과 함께 반응하도록 설계합니다.", 19),
      ]),
      modulePlan("포털과 환경 VFX", [
        lessonPlan("원형 포털 머티리얼", "마스크, 노이즈, emissive를 이용해 포털 표면을 만듭니다.", 23),
        lessonPlan("공간을 채우는 에너지 입자", "포털 주변을 도는 입자와 빛줄기를 구성합니다.", 21),
        lessonPlan("안개, 먼지, 낙엽 같은 환경 이펙트", "월드 분위기를 만드는 저강도 이펙트를 만듭니다.", 20),
        lessonPlan("시퀀서로 이펙트 쇼케이스", "포트폴리오용 짧은 VFX 클립을 카메라와 함께 렌더링합니다.", 22, ["vfx-showcase-plan.pdf"]),
      ]),
      modulePlan("최적화와 포트폴리오", [
        lessonPlan("이펙트 비용을 보는 기준", "Overdraw, particle count, tick cost를 확인합니다.", 22),
        lessonPlan("LOD와 Scalability 설정", "기기 성능에 따라 이펙트 품질을 조절합니다.", 20),
        lessonPlan("실제 게임 이벤트에 붙이기", "캐릭터 공격, 스킬 발동, 피격 이벤트에 Niagara를 연결합니다.", 21),
        lessonPlan("VFX 포트폴리오 정리", "대표 이펙트, breakdown, 영상 캡처를 구성합니다.", 19, ["vfx-portfolio-checklist.pdf"]),
      ]),
      modulePlan("스킬 이펙트 쇼케이스 제작", [
        lessonPlan("스킬 3종 세트 기획", "근접 공격, 원거리 투사체, 광역 스킬을 하나의 세트로 구성합니다.", 20),
        lessonPlan("이펙트 타이밍 맞추기", "캐릭터 모션과 파티클이 어긋나지 않도록 타임라인을 조정합니다.", 21),
        lessonPlan("배경과 이펙트 대비 조절", "어두운 배경과 밝은 파티클 사이의 가독성을 다듬습니다.", 20),
        lessonPlan("쇼릴 영상으로 렌더링", "포트폴리오용 20초 VFX 쇼릴을 캡처하고 정리합니다.", 19),
      ]),
    ]),
  },
  ...additionalGameCourses,
]

export function findMockCourse(id: number) {
  const source = mockCourses.find((item) => item.id === id)
  if (!source) return null
  const course = withDerivedMockStats(source)
  const availability = getEnrollmentAvailability(course)
  return {
    ...course,
    enrollmentStatus: availability.status,
    enrollmentAvailable: availability.isAvailable,
    remainingSeats: availability.remainingSeats,
  }
}

export function getMockCoursesWithEnrollmentStatus() {
  return mockCourses.map((course) => findMockCourse(course.id)!)
}
