import { getEnrollmentAvailability, type EnrollmentAvailabilityStatus } from "@/lib/enrollment-window"

export type MockCourse = {
  id: number
  title: string
  slug: string
  shortDescription: string
  description: string
  category: string
  level: string
  languageCode: string
  tags: string[]
  seoKeywords: string[]
  targetAudience: string
  requirements: string
  learningOutcomes: string[]
  metaTitle: string
  metaDescription: string
  ogImageUrl: string
  canonicalUrl: string | null
  enrollmentOpen: boolean
  enrollmentStartAt: string | null
  enrollmentEndAt: string | null
  enrollmentCapacity: number | null
  enrollmentAppliedCount: number
  enrollmentStatus?: EnrollmentAvailabilityStatus
  enrollmentAvailable?: boolean
  remainingSeats?: number | null
  price: number
  discountPrice: number | null
  imageUrl: string
  createdAt: string
  purchaseCount: number
  reviewCount: number
  avgRating: number
  likeCount: number
  instructor: { id: number; nickname: string; email: string; profileImageUrl?: string | null }
  sections: Array<{ id: number; title: string; description: string; active: boolean; hasVideo: boolean; hlsStatus: string | null }>
}

export const previewImages = [
  "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
]

export const mockCourses: MockCourse[] = [
  {
    id: 101,
    title: "Next.js로 강의 거래소 만들기",
    slug: "nextjs-course-marketplace",
    shortDescription: "상품, 수강신청, 계좌입금 승인, SEO까지 웹 플랫폼의 뼈대를 완성합니다.",
    description: "웹 우선 강의 플랫폼을 직접 만들며 서비스 구조를 익힙니다. 판매 페이지, 모집 기간, 입금 확인 기반 수강 승인까지 실제 운영 흐름으로 배웁니다.",
    category: "웹 개발",
    level: "중급",
    languageCode: "ko",
    tags: ["Next.js", "Drizzle", "SEO"],
    seoKeywords: ["Next.js 강의", "강의 플랫폼", "Drizzle ORM", "SEO"],
    targetAudience: "직접 강의 플랫폼을 만들고 싶은 개발자와 1인 창업자",
    requirements: "React와 TypeScript 기초 지식",
    learningOutcomes: ["강의 목록과 상세 페이지 설계", "SEO 메타데이터 구성", "수강신청 흐름 이해"],
    metaTitle: "Next.js로 강의 거래소 만들기 | 박살강의",
    metaDescription: "Next.js, Drizzle, SEO 기반으로 강의 거래소의 핵심 구조를 만드는 강의입니다.",
    ogImageUrl: previewImages[0],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-10T00:00:00.000Z",
    enrollmentEndAt: "2026-06-05T14:59:59.000Z",
    enrollmentCapacity: 40,
    enrollmentAppliedCount: 27,
    price: 99000,
    discountPrice: 69000,
    imageUrl: previewImages[0],
    createdAt: "2026-05-01T00:00:00.000Z",
    purchaseCount: 1240,
    reviewCount: 186,
    avgRating: 4.88,
    likeCount: 342,
    instructor: { id: 9001, nickname: "박살랩", email: "studio@baksalclass.com" },
    sections: [
      { id: 10101, title: "마켓플레이스 구조 잡기", description: "수강생, 판매자, 최고 관리자 역할을 나눕니다.", active: true, hasVideo: false, hlsStatus: null },
      { id: 10102, title: "SEO와 강의 상세", description: "검색되는 강의 페이지의 필드를 설계합니다.", active: true, hasVideo: false, hlsStatus: null },
      { id: 10103, title: "수강신청 흐름", description: "입금 확인 전후 권한 부여 흐름을 만듭니다.", active: true, hasVideo: false, hlsStatus: null },
    ],
  },
  {
    id: 102,
    title: "HLS 스트리밍과 영상 운영",
    slug: "hls-video-operations",
    shortDescription: "ffmpeg, HLS, 자막, 더빙 트랙을 강의 서비스 흐름에 맞게 설계합니다.",
    description: "동영상 강의를 판매할 때 필요한 HLS 운영 전략을 다룹니다. 로컬 인코딩 승인 플로우를 기준으로 설명합니다.",
    category: "미디어",
    level: "고급",
    languageCode: "ko",
    tags: ["HLS", "FFmpeg", "Caption"],
    seoKeywords: ["HLS 강의", "FFmpeg", "영상 인코딩", "자막"],
    targetAudience: "영상 기반 교육 서비스를 운영하려는 개발자와 강의 판매자",
    requirements: "기본적인 파일 업로드와 웹 비디오 개념",
    learningOutcomes: ["HLS 변환 흐름 이해", "자막 트랙 운영", "로컬 인코딩 승인 방식 설계"],
    metaTitle: "HLS 스트리밍과 영상 운영 | 박살강의",
    metaDescription: "강의 플랫폼에서 HLS, 자막, 더빙 트랙을 운영하는 방법을 다루는 강의입니다.",
    ogImageUrl: previewImages[1],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-01T00:00:00.000Z",
    enrollmentEndAt: "2026-05-28T14:59:59.000Z",
    enrollmentCapacity: 24,
    enrollmentAppliedCount: 24,
    price: 129000,
    discountPrice: null,
    imageUrl: previewImages[1],
    createdAt: "2026-05-02T00:00:00.000Z",
    purchaseCount: 520,
    reviewCount: 73,
    avgRating: 4.91,
    likeCount: 189,
    instructor: { id: 9002, nickname: "스트림마스터", email: "stream@baksalclass.com" },
    sections: [
      { id: 10201, title: "왜 HLS인가", description: "브라우저 재생과 적응형 스트리밍을 이해합니다.", active: true, hasVideo: false, hlsStatus: null },
      { id: 10202, title: "로컬 인코딩 운영", description: "관리자 승인 시점에 인코딩을 실행하는 구조를 봅니다.", active: true, hasVideo: false, hlsStatus: null },
    ],
  },
  {
    id: 103,
    title: "AI 시대 판매되는 강의 기획법",
    slug: "ai-course-planning",
    shortDescription: "검색되는 커리큘럼, 전환되는 상세 페이지, 완주율 높은 수업 설계.",
    description: "강의 판매자가 콘텐츠를 시장에 맞게 설계하는 법을 배웁니다. 검색 의도와 공개 영상 구성, 판매 페이지 카피까지 한 번에 정리합니다.",
    category: "크리에이터",
    level: "입문",
    languageCode: "ko",
    tags: ["기획", "마케팅", "커리큘럼"],
    seoKeywords: ["강의 기획", "온라인 강의 판매", "커리큘럼 설계", "AI 강의"],
    targetAudience: "첫 강의를 준비하는 크리에이터와 전문가",
    requirements: "팔고 싶은 주제와 간단한 촬영 도구",
    learningOutcomes: ["판매되는 강의 주제 선정", "검색 의도 기반 목차 구성", "상세 페이지 전환 포인트 설계"],
    metaTitle: "AI 시대 판매되는 강의 기획법 | 박살강의",
    metaDescription: "검색되는 커리큘럼과 전환되는 상세 페이지를 설계하는 강의 기획 강의입니다.",
    ogImageUrl: previewImages[2],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-08T00:00:00.000Z",
    enrollmentEndAt: "2026-06-12T14:59:59.000Z",
    enrollmentCapacity: 60,
    enrollmentAppliedCount: 41,
    price: 59000,
    discountPrice: 39000,
    imageUrl: previewImages[2],
    createdAt: "2026-05-03T00:00:00.000Z",
    purchaseCount: 870,
    reviewCount: 92,
    avgRating: 4.74,
    likeCount: 277,
    instructor: { id: 9003, nickname: "콘텐츠빌더", email: "creator@baksalclass.com" },
    sections: [
      { id: 10301, title: "팔리는 주제의 조건", description: "전문성, 수요, 검색 가능성을 같이 봅니다.", active: true, hasVideo: false, hlsStatus: null },
      { id: 10302, title: "커리큘럼을 상품으로 바꾸기", description: "수업 목록을 구매 이유로 연결합니다.", active: true, hasVideo: false, hlsStatus: null },
      { id: 10303, title: "상세 페이지 카피", description: "첫 화면에서 신뢰를 만드는 문장을 설계합니다.", active: true, hasVideo: false, hlsStatus: null },
    ],
  },
  {
    id: 104,
    title: "수강생이 끝까지 보는 강의 편집",
    slug: "course-editing-retention",
    shortDescription: "긴 영상보다 오래 남는 리듬, 챕터, 대표 이미지를 설계합니다.",
    description: "촬영 이후 실제 판매 페이지에 올라가는 결과물을 다듬습니다.",
    category: "디자인",
    level: "입문",
    languageCode: "ko",
    tags: ["편집", "썸네일", "완주율"],
    seoKeywords: ["강의 편집", "온라인 강의 썸네일", "완주율"],
    targetAudience: "강의 영상을 더 보기 좋게 만들고 싶은 판매자",
    requirements: "기본적인 영상 편집 툴",
    learningOutcomes: ["챕터 구조화", "대표 이미지 구성", "완주율을 높이는 편집 리듬"],
    metaTitle: "수강생이 끝까지 보는 강의 편집 | 박살강의",
    metaDescription: "강의 영상의 리듬, 챕터, 대표 이미지를 설계하는 강의입니다.",
    ogImageUrl: previewImages[3],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-04-15T00:00:00.000Z",
    enrollmentEndAt: "2026-05-12T14:59:59.000Z",
    enrollmentCapacity: 30,
    enrollmentAppliedCount: 22,
    price: 79000,
    discountPrice: 59000,
    imageUrl: previewImages[3],
    createdAt: "2026-05-04T00:00:00.000Z",
    purchaseCount: 438,
    reviewCount: 61,
    avgRating: 4.82,
    likeCount: 164,
    instructor: { id: 9004, nickname: "컷앤런", email: "edit@baksalclass.com" },
    sections: [{ id: 10401, title: "강의 편집의 기준", description: "지루함을 줄이는 편집 원칙을 잡습니다.", active: true, hasVideo: false, hlsStatus: null }],
  },
  {
    id: 105,
    title: "강의 판매자를 위한 SEO 실전",
    slug: "course-seo-practice",
    shortDescription: "태그, 메타 타이틀, 사이트맵, 검색 의도를 강의 등록 폼에 녹입니다.",
    description: "강의가 검색 결과에 남도록 구조화하는 방법을 다룹니다.",
    category: "비즈니스",
    level: "중급",
    languageCode: "ko",
    tags: ["SEO", "검색", "콘텐츠"],
    seoKeywords: ["강의 SEO", "메타 타이틀", "사이트맵", "콘텐츠 SEO"],
    targetAudience: "강의를 검색 결과에 노출시키고 싶은 판매자",
    requirements: "등록할 강의 주제와 키워드 후보",
    learningOutcomes: ["SEO 필드 작성", "검색 의도 매칭", "강의 상세 구조화"],
    metaTitle: "강의 판매자를 위한 SEO 실전 | 박살강의",
    metaDescription: "강의 등록 시 필요한 SEO 필드를 실전적으로 작성하는 강의입니다.",
    ogImageUrl: previewImages[4],
    canonicalUrl: null,
    enrollmentOpen: false,
    enrollmentStartAt: "2026-06-20T00:00:00.000Z",
    enrollmentEndAt: "2026-07-05T14:59:59.000Z",
    enrollmentCapacity: 35,
    enrollmentAppliedCount: 0,
    price: 89000,
    discountPrice: null,
    imageUrl: previewImages[4],
    createdAt: "2026-05-05T00:00:00.000Z",
    purchaseCount: 312,
    reviewCount: 44,
    avgRating: 4.79,
    likeCount: 121,
    instructor: { id: 9005, nickname: "검색설계자", email: "seo@baksalclass.com" },
    sections: [{ id: 10501, title: "강의 SEO 체크리스트", description: "노출에 필요한 필드를 하나씩 채웁니다.", active: true, hasVideo: false, hlsStatus: null }],
  },
  {
    id: 106,
    title: "자동 더빙과 다국어 강의 운영",
    slug: "ai-dubbing-course-operations",
    shortDescription: "ElevenLabs 기반 더빙을 수업 단위로 승인하고 운영하는 실전 플로우.",
    description: "다국어 오디오 트랙을 운영하고 관리하는 방식을 배웁니다.",
    category: "AI",
    level: "고급",
    languageCode: "ko",
    tags: ["AI", "더빙", "글로벌"],
    seoKeywords: ["AI 더빙", "ElevenLabs", "다국어 강의"],
    targetAudience: "국내 강의를 해외로 확장하고 싶은 판매자",
    requirements: "원본 강의 영상과 대본",
    learningOutcomes: ["더빙 승인 흐름", "언어 트랙 관리", "자막과 음성의 역할 분리"],
    metaTitle: "자동 더빙과 다국어 강의 운영 | 박살강의",
    metaDescription: "ElevenLabs 기반 자동 더빙과 다국어 강의 운영 흐름을 보는 강의입니다.",
    ogImageUrl: previewImages[5],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-18T00:00:00.000Z",
    enrollmentEndAt: "2026-06-30T14:59:59.000Z",
    enrollmentCapacity: 18,
    enrollmentAppliedCount: 6,
    price: 119000,
    discountPrice: 99000,
    imageUrl: previewImages[5],
    createdAt: "2026-05-06T00:00:00.000Z",
    purchaseCount: 284,
    reviewCount: 39,
    avgRating: 4.86,
    likeCount: 118,
    instructor: { id: 9006, nickname: "보이스빌더", email: "voice@baksalclass.com" },
    sections: [{ id: 10601, title: "더빙 운영 구조", description: "자동화와 수동 승인의 경계를 정합니다.", active: true, hasVideo: false, hlsStatus: null }],
  },
  {
    id: 107,
    title: "1인 강사의 정산과 운영 장부",
    slug: "solo-instructor-ledger",
    shortDescription: "수강신청, 입금 확인, 정산 기준, 수동 승인까지 설계합니다.",
    description: "초기 마켓플레이스 운영에 필요한 장부 흐름을 만듭니다.",
    category: "비즈니스",
    level: "입문",
    languageCode: "ko",
    tags: ["정산", "입금확인", "운영"],
    seoKeywords: ["강의 정산", "수동 입금 확인", "마켓플레이스 운영"],
    targetAudience: "초기 수동 정산으로 강의 플랫폼을 운영하려는 창업자",
    requirements: "기본적인 매출/정산 개념",
    learningOutcomes: ["정산 기준 기록", "수동 입금 승인", "정산 큐 설계"],
    metaTitle: "1인 강사의 정산과 운영 장부 | 박살강의",
    metaDescription: "초기 강의 플랫폼의 입금 확인, 운영 정산, 수동 승인 흐름을 다루는 강의입니다.",
    ogImageUrl: previewImages[6],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-05-01T00:00:00.000Z",
    enrollmentEndAt: "2026-05-30T14:59:59.000Z",
    enrollmentCapacity: 50,
    enrollmentAppliedCount: 11,
    price: 49000,
    discountPrice: 0,
    imageUrl: previewImages[6],
    createdAt: "2026-05-07T00:00:00.000Z",
    purchaseCount: 156,
    reviewCount: 21,
    avgRating: 4.67,
    likeCount: 77,
    instructor: { id: 9007, nickname: "운영노트", email: "ops@baksalclass.com" },
    sections: [{ id: 10701, title: "정산 장부의 최소 구조", description: "초기 운영자가 꼭 봐야 하는 데이터를 정의합니다.", active: true, hasVideo: false, hlsStatus: null }],
  },
  {
    id: 108,
    title: "초보 판매자용 첫 강의 출시",
    slug: "first-course-launch",
    shortDescription: "한 편의 공개 영상에서 첫 유료 커리큘럼까지 필요한 최소 단계를 정리합니다.",
    description: "강의를 처음 파는 사람에게 필요한 등록과 출시 체크리스트입니다.",
    category: "크리에이터",
    level: "입문",
    languageCode: "ko",
    tags: ["출시", "공개영상", "판매"],
    seoKeywords: ["첫 강의 출시", "강의 판매", "공개 강의"],
    targetAudience: "첫 유료 강의를 출시하려는 초보 판매자",
    requirements: "판매할 주제와 1개 이상의 공개 영상",
    learningOutcomes: ["출시 체크리스트", "공개 영상 구성", "판매 페이지 기본 필드"],
    metaTitle: "초보 판매자용 첫 강의 출시 | 박살강의",
    metaDescription: "첫 강의 출시를 위한 등록, 공개 영상, 판매 페이지 체크리스트 강의입니다.",
    ogImageUrl: previewImages[7],
    canonicalUrl: null,
    enrollmentOpen: true,
    enrollmentStartAt: "2026-06-01T00:00:00.000Z",
    enrollmentEndAt: "2026-06-21T14:59:59.000Z",
    enrollmentCapacity: 45,
    enrollmentAppliedCount: 0,
    price: 69000,
    discountPrice: 49000,
    imageUrl: previewImages[7],
    createdAt: "2026-05-08T00:00:00.000Z",
    purchaseCount: 221,
    reviewCount: 28,
    avgRating: 4.7,
    likeCount: 93,
    instructor: { id: 9008, nickname: "첫강의클럽", email: "launch@baksalclass.com" },
    sections: [{ id: 10801, title: "첫 출시의 순서", description: "강의 등록부터 공개까지 필요한 단계를 정리합니다.", active: true, hasVideo: false, hlsStatus: null }],
  },
]

export function findMockCourse(id: number) {
  const course = mockCourses.find((item) => item.id === id)
  if (!course) return null
  const availability = getEnrollmentAvailability(course)
  return {
    ...course,
    enrollmentStatus: availability.status,
    enrollmentAvailable: availability.isAvailable,
    remainingSeats: availability.remainingSeats,
  }
}

export function getMockCoursesWithEnrollmentStatus() {
  return mockCourses.map((course) => findMockCourse(course.id)!)
}
